In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount("/content/drive")
pd.set_option("display.max_columns", None)

taman_surabaya = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_surabaya.csv")
taman_sidoarjo = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_sidoarjo.csv")
taman_mojokerto = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_mojokerto.csv")
taman_jombang = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_jombang.csv")
taman_nganjuk = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_nganjuk.csv")
taman_bojonegoro = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_bojonegoro.csv")
taman_tuban = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_tuban.csv")
taman_kediri = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_kediri.csv")
taman_pasuruan = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_pasuruan.csv")
taman_gresik = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_gresik.csv")

museum_surabaya = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_surabaya.csv")
museum_sidoarjo = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_sidoarjo.csv")
museum_mojokerto = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_mojokerto.csv")
museum_jombang = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_jombang.csv")
museum_nganjuk = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_nganjuk.csv")
museum_bojonegoro = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_bojonegoro.csv")
museum_tuban = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_tuban.csv")
museum_kediri = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_kediri.csv")
museum_pasuruan = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_pasuruan.csv")
museum_gresik = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_gresik.csv")

Mounted at /content/drive

In [2]:
tmp_taman = pd.DataFrame()
tmp_museum = pd.DataFrame()

# Taman Surabaya

In [3]:
tmp = taman_surabaya.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Astoria Park,"PQVP+GM4, Jl. Babatan Pantai Bar V, Kalijudan,...",5,https://www.google.com/maps/place/Astoria+Park...,Jawa Timur 60114,Kota SBY,Kec. Mulyorejo
1,Asia Goldfish Surabaya,"Jl. Raya Medayu Utara Kav. No. 1 Gerbang biru,...","4,7",https://www.google.com/maps/place/Asia+Goldfis...,Jawa Timur 60295,Kota SBY,Kec. Rungkut
3,Taman Bermain & Lapangan Futsal,"PJWW+P27, Sememi, Kec. Benowo, Kota SBY, Jawa ...","4,3",https://www.google.com/maps/place/Taman+Bermai...,Jawa Timur 60198,Kota SBY,Kec. Benowo
4,Taman Ekspresi Dan Perpustakaan,"Jl. Genteng Kali No.67, Genteng, Kec. Genteng,...","4,5",https://www.google.com/maps/place/Taman+Ekspre...,Jawa Timur 60275,Kota SBY,Kec. Genteng
5,Wisata Mangrove Wonorejo Surabaya,"No., Jl. Wonorejo Timur No.30, Wonorejo, Kec. ...","4,5",https://www.google.com/maps/place/Wisata+Mangr...,Jawa Timur 60296,Kota SBY,Kec. Rungkut

In [4]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0      Jawa Timur
1      Jawa Timur
3      Jawa Timur
4      Jawa Timur
5      Jawa Timur
          ...
115    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 100, dtype: category
Categories (1, object): ['Jawa Timur']

In [5]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Sidoarjo"].index, inplace=True)
tmp["Kota"].replace(["Kota SBY", "Surabaya City"], "Surabaya", inplace=True)
tmp["Kota"].astype("category")

0      Surabaya
1      Surabaya
3      Surabaya
4      Surabaya
5      Surabaya
         ...
115    Surabaya
116    Surabaya
117    Surabaya
118    Surabaya
119    Surabaya
Name: Kota, Length: 99, dtype: category
Categories (1, object): ['Surabaya']

In [6]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0      Mulyorejo
1        Rungkut
3         Benowo
4        Genteng
5        Rungkut
         ...
115      Genteng
116    Wonokromo
117     Gayungan
118        Bulak
119        Bulak
Name: Kecamatan, Length: 99, dtype: category
Categories (25, object): ['Benowo', 'Bubutan', 'Bulak', 'Dukuhpakis', ..., 'Tegalsari', 'Wiyung',
                          'Wonocolo', 'Wonokromo']

In [7]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Astoria Park,"PQVP+GM4, Jl. Babatan Pantai Bar V, Kalijudan,...",5.0,https://www.google.com/maps/place/Astoria+Park...,Jawa Timur,Surabaya,Mulyorejo
1,Asia Goldfish Surabaya,"Jl. Raya Medayu Utara Kav. No. 1 Gerbang biru,...",4.7,https://www.google.com/maps/place/Asia+Goldfis...,Jawa Timur,Surabaya,Rungkut
3,Taman Bermain & Lapangan Futsal,"PJWW+P27, Sememi, Kec. Benowo, Kota SBY, Jawa ...",4.3,https://www.google.com/maps/place/Taman+Bermai...,Jawa Timur,Surabaya,Benowo
4,Taman Ekspresi Dan Perpustakaan,"Jl. Genteng Kali No.67, Genteng, Kec. Genteng,...",4.5,https://www.google.com/maps/place/Taman+Ekspre...,Jawa Timur,Surabaya,Genteng
5,Wisata Mangrove Wonorejo Surabaya,"No., Jl. Wonorejo Timur No.30, Wonorejo, Kec. ...",4.5,https://www.google.com/maps/place/Wisata+Mangr...,Jawa Timur,Surabaya,Rungkut

In [8]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Sidoarjo

In [9]:
tmp = taman_sidoarjo.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
1,Heavenland Park Cluster Palmyra D 19,"Klurak, Kec. Candi, Kabupaten Sidoarjo, Jawa T...","4,6",https://www.google.com/maps/place/Heavenland+P...,Jawa Timur 61271,Kabupaten Sidoarjo,Kec. Candi
2,Park Royal Regency Q2/16,Park Royal Regency Q2/16 Park Royal Regency Q2...,4,https://www.google.com/maps/place/Park+Royal+R...,East Java 61252,Sidoarjo Regency,Buduran
3,Hutan Kota Delta Putri,"GPX7+MC8, Jl. Pahlawan, Rw6, Sidokumpul, Kec. ...","3,6",https://www.google.com/maps/place/Hutan+Kota+D...,Jawa Timur 61212,Kabupaten Sidoarjo,Kec. Sidoarjo
4,Heavenland Park Cluster Aragon,"GP8F+WJM, Sawah, Klurak, Kec. Candi, Kabupaten...","4,7",https://www.google.com/maps/place/Heavenland+P...,Jawa Timur 61271,Kabupaten Sidoarjo,Kec. Candi
7,Musholla Al Hidayah Park Royal Reg Buduran Sid...,"HPC5+622, Irianjaya, Pagerwojo, Kec. Buduran, ...",5,https://www.google.com/maps/place/Musholla+Al+...,Jawa Timur 61252,Kabupaten Sidoarjo,Kec. Buduran

In [10]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

1      Jawa Timur
2      Jawa Timur
3      Jawa Timur
4      Jawa Timur
7      Jawa Timur
          ...
115    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 99, dtype: category
Categories (1, object): ['Jawa Timur']

In [11]:
tmp["Kota"].replace(["Kabupaten Sidoarjo", "Sidoarjo Regency"], "Sidoarjo", inplace=True)
tmp["Kota"].astype("category")

1      Sidoarjo
2      Sidoarjo
3      Sidoarjo
4      Sidoarjo
7      Sidoarjo
         ...
115    Sidoarjo
116    Sidoarjo
117    Sidoarjo
118    Sidoarjo
119    Sidoarjo
Name: Kota, Length: 99, dtype: category
Categories (1, object): ['Sidoarjo']

In [12]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

1         Candi
2       Buduran
3      Sidoarjo
4         Candi
7       Buduran
         ...
115      Sedati
116    Sukodono
117        Waru
118    Sidoarjo
119     Buduran
Name: Kecamatan, Length: 99, dtype: category
Categories (12, object): ['BalongBendo', 'Buduran', 'Candi', 'Gedangan', ..., 'Taman', 'Tanggulangin',
                          'Waru', 'Wonoayu']

In [13]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
1,Heavenland Park Cluster Palmyra D 19,"Klurak, Kec. Candi, Kabupaten Sidoarjo, Jawa T...",4.6,https://www.google.com/maps/place/Heavenland+P...,Jawa Timur,Sidoarjo,Candi
2,Park Royal Regency Q2/16,Park Royal Regency Q2/16 Park Royal Regency Q2...,4.0,https://www.google.com/maps/place/Park+Royal+R...,Jawa Timur,Sidoarjo,Buduran
3,Hutan Kota Delta Putri,"GPX7+MC8, Jl. Pahlawan, Rw6, Sidokumpul, Kec. ...",3.6,https://www.google.com/maps/place/Hutan+Kota+D...,Jawa Timur,Sidoarjo,Sidoarjo
4,Heavenland Park Cluster Aragon,"GP8F+WJM, Sawah, Klurak, Kec. Candi, Kabupaten...",4.7,https://www.google.com/maps/place/Heavenland+P...,Jawa Timur,Sidoarjo,Candi
7,Musholla Al Hidayah Park Royal Reg Buduran Sid...,"HPC5+622, Irianjaya, Pagerwojo, Kec. Buduran, ...",5.0,https://www.google.com/maps/place/Musholla+Al+...,Jawa Timur,Sidoarjo,Buduran

In [14]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Mojokerto

In [15]:
tmp = taman_mojokerto.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Taman SWARGALOKA Dlanggu,"CFMP+G9W, Lebak, Dlanggu, Kec. Dlanggu, Kabupa...",5,https://www.google.com/maps/place/Taman+SWARGA...,Jawa Timur 61371,Kabupaten Mojokerto,Kec. Dlanggu
1,Gantangan SKMM (Seduluran Kicau Mania Mojopahit),"GCVP+582, Lespadangan, Terusan, Kec. Gedek, Ka...",5,https://www.google.com/maps/place/Gantangan+SK...,Jawa Timur 61351,Kabupaten Mojokerto,Kec. Gedek
3,Omah Green Park,"G42, Jl. Raya Jetis, Wonorejo, Jetis, Kec. Jet...",1,https://www.google.com/maps/place/Omah+Green+P...,Jawa Timur 61352,Kabupaten Mojokerto,Kec. Jetis
5,Petik Jeruk Pak Janan,"G93V+VCV, Sasap, Modongan, Kec. Sooko, Kabupat...","3,9",https://www.google.com/maps/place/Petik+Jeruk+...,Jawa Timur 61361,Kabupaten Mojokerto,Kec. Sooko
6,Sawah ijo,"CF99+R7H, Area Sawah/Kebun, Talok, Kec. Dlangg...",5,https://www.google.com/maps/place/Sawah+ijo/@-...,Jawa Timur,Kabupaten Mojokerto,Kec. Dlanggu

In [16]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0      Jawa Timur
1      Jawa Timur
3      Jawa Timur
5      Jawa Timur
6      Jawa Timur
          ...
113    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 80, dtype: category
Categories (1, object): ['Jawa Timur']

In [17]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Gresik"].index, inplace=True)
tmp["Kota"].replace(["Kabupaten Mojokerto", "Kota Mojokerto", "Mojokerto Regency"], "Mojokerto", inplace=True)
tmp["Kota"].astype("category")

0      Mojokerto
1      Mojokerto
3      Mojokerto
5      Mojokerto
6      Mojokerto
         ...
113    Mojokerto
116    Mojokerto
117    Mojokerto
118    Mojokerto
119    Mojokerto
Name: Kota, Length: 79, dtype: category
Categories (1, object): ['Mojokerto']

In [18]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0             Dlanggu
1               Gedek
3               Jetis
5               Sooko
6             Dlanggu
            ...
113             Pacet
116             Sooko
117         Magersari
118         Magersari
119    Prajurit Kulon
Name: Kecamatan, Length: 79, dtype: category
Categories (14, object): ['Dlanggu', 'Gedek', 'Gondang', 'Jetis', ..., 'Pungging', 'Sooko', 'Trawas',
                          'Trowulan']

In [19]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Taman SWARGALOKA Dlanggu,"CFMP+G9W, Lebak, Dlanggu, Kec. Dlanggu, Kabupa...",5.0,https://www.google.com/maps/place/Taman+SWARGA...,Jawa Timur,Mojokerto,Dlanggu
1,Gantangan SKMM (Seduluran Kicau Mania Mojopahit),"GCVP+582, Lespadangan, Terusan, Kec. Gedek, Ka...",5.0,https://www.google.com/maps/place/Gantangan+SK...,Jawa Timur,Mojokerto,Gedek
3,Omah Green Park,"G42, Jl. Raya Jetis, Wonorejo, Jetis, Kec. Jet...",1.0,https://www.google.com/maps/place/Omah+Green+P...,Jawa Timur,Mojokerto,Jetis
5,Petik Jeruk Pak Janan,"G93V+VCV, Sasap, Modongan, Kec. Sooko, Kabupat...",3.9,https://www.google.com/maps/place/Petik+Jeruk+...,Jawa Timur,Mojokerto,Sooko
6,Sawah ijo,"CF99+R7H, Area Sawah/Kebun, Talok, Kec. Dlangg...",5.0,https://www.google.com/maps/place/Sawah+ijo/@-...,Jawa Timur,Mojokerto,Dlanggu

In [20]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Jombang

In [21]:
tmp = taman_jombang.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Berkah Rodjokojo Farm,"C739+VP2, Unnamed Road, Sumberbendo, Jogoroto,...","4,2",https://www.google.com/maps/place/Berkah+Rodjo...,Jawa Timur 61485,Kabupaten Jombang,Kec. Jogoroto
1,Wisata Bajak Laut 2,"Area Sawah/Kebun, Sumberjo, Kec. Wonosalam, Ka...","4,1",https://www.google.com/maps/place/Wisata+Bajak...,Jawa Timur 61476,Kabupaten Jombang,Kec. Wonosalam
2,Taman Brantas Indah,"No., Jl. Mager Sari-Ngares Kidul No.14, Lorsar...","4,1",https://www.google.com/maps/place/Taman+Branta...,Jawa Timur 61352,Kabupaten Mojokerto,Kec. Jetis
3,Wanawisata Gua Sigolo-Golo,"8CG5+8XW Sigolo-golo Eco Park, Area Sawah/Kebu...","4,1",https://www.google.com/maps/place/Wanawisata+G...,Jawa Timur 61476,Kabupaten Jombang,Kec. Wonosalam
4,Taman Logo NU,"Jl. Raya Mojoagung No.90, Gambiran Utara, Gamb...","4,7",https://www.google.com/maps/place/Taman+Logo+N...,Jawa Timur 61482,Kabupaten Jombang,Kec. Mojoagung

In [22]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0      Jawa Timur
1      Jawa Timur
2      Jawa Timur
3      Jawa Timur
4      Jawa Timur
          ...
114    Jawa Timur
115    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 81, dtype: category
Categories (1, object): ['Jawa Timur']

In [23]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Mojokerto"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Nganjuk"].index, inplace=True)
tmp["Kota"].replace(["Kabupaten Jombang", "Jombang Regency"], "Jombang", inplace=True)
tmp["Kota"].astype("category")

0      Jombang
1      Jombang
3      Jombang
4      Jombang
5      Jombang
        ...
114    Jombang
115    Jombang
117    Jombang
118    Jombang
119    Jombang
Name: Kota, Length: 79, dtype: category
Categories (1, object): ['Jombang']

In [24]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0               Jogoroto
1              Wonosalam
3              Wonosalam
4              Mojoagung
5                  Diwek
             ...
114              Jombang
115    Bandarkedungmulyo
117              Jombang
118           Peterongan
119              Jombang
Name: Kecamatan, Length: 79, dtype: category
Categories (18, object): ['Bandarkedungmulyo', 'Bareng', 'Diwek', 'Gudo', ..., 'Ploso', 'Sumobito', 'Tembelang',
                          'Wonosalam']

In [25]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Berkah Rodjokojo Farm,"C739+VP2, Unnamed Road, Sumberbendo, Jogoroto,...",4.2,https://www.google.com/maps/place/Berkah+Rodjo...,Jawa Timur,Jombang,Jogoroto
1,Wisata Bajak Laut 2,"Area Sawah/Kebun, Sumberjo, Kec. Wonosalam, Ka...",4.1,https://www.google.com/maps/place/Wisata+Bajak...,Jawa Timur,Jombang,Wonosalam
3,Wanawisata Gua Sigolo-Golo,"8CG5+8XW Sigolo-golo Eco Park, Area Sawah/Kebu...",4.1,https://www.google.com/maps/place/Wanawisata+G...,Jawa Timur,Jombang,Wonosalam
4,Taman Logo NU,"Jl. Raya Mojoagung No.90, Gambiran Utara, Gamb...",4.7,https://www.google.com/maps/place/Taman+Logo+N...,Jawa Timur,Jombang,Mojoagung
5,WISATA SUMBER CELENG,"97C7+HCX, Area Sawah/Kebun, Bulurejo, Kec. Diw...",4.1,https://www.google.com/maps/place/WISATA+SUMBE...,Jawa Timur,Jombang,Diwek

In [26]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Nganjuk

In [27]:
tmp = taman_nganjuk.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
1,LAPANGAN SEPAKBOLA TANJUNG LOCERET,"Pugruk, Tanjungrejo, Kec. Loceret, Kabupaten N...",4,https://www.google.com/maps/place/LAPANGAN+SEP...,Jawa Timur 64471,Kabupaten Nganjuk,Kec. Loceret
2,Taman Bibit,"Waung, Kec. Baron, Kabupaten Nganjuk, Jawa Tim...","4,2",https://www.google.com/maps/place/Taman+Bibit/...,Jawa Timur 64394,Kabupaten Nganjuk,Kec. Baron
3,Gantangan Guyangan BC Reborn,"CV9H+C25, Guyangan, Kec. Bagor, Kabupaten Ngan...",5,https://www.google.com/maps/place/Gantangan+Gu...,Jawa Timur 64461,Kabupaten Nganjuk,Kec. Bagor
4,Wisata Gondali View,"7V8P+2J7, Jl. Sumberklampok, Sanan, Macanan, K...",5,https://www.google.com/maps/place/Wisata+Gonda...,Jawa Timur 64471,Kabupaten Nganjuk,Kec. Loceret
5,Puncak Tapan 11,"6Q9Q+C6C, Unnamed Road, Hutan, Bareng, Sawahan...","4,8",https://www.google.com/maps/place/Puncak+Tapan...,East Java 64475,Nganjuk Regency,Sawahan

In [28]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

1      Jawa Timur
2      Jawa Timur
3      Jawa Timur
4      Jawa Timur
5      Jawa Timur
          ...
115    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 80, dtype: category
Categories (1, object): ['Jawa Timur']

In [29]:
tmp["Kota"].replace(["Kabupaten Nganjuk", "Nganjuk Regency"], "Nganjuk", inplace=True)
tmp["Kota"].astype("category")

1      Nganjuk
2      Nganjuk
3      Nganjuk
4      Nganjuk
5      Nganjuk
        ...
115    Nganjuk
116    Nganjuk
117    Nganjuk
118    Nganjuk
119    Nganjuk
Name: Kota, Length: 80, dtype: category
Categories (1, object): ['Nganjuk']

In [30]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

1      Loceret
2        Baron
3        Bagor
4      Loceret
5      Sawahan
        ...
115    Nganjuk
116    Nganjuk
117    Nganjuk
118    Nganjuk
119     Berbek
Name: Kecamatan, Length: 80, dtype: category
Categories (16, object): ['Bagor', 'Baron', 'Berbek', 'Gondang', ..., 'Rejoso', 'Sawahan',
                          'Tanjunganom', 'Wilangan']

In [31]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
1,LAPANGAN SEPAKBOLA TANJUNG LOCERET,"Pugruk, Tanjungrejo, Kec. Loceret, Kabupaten N...",4.0,https://www.google.com/maps/place/LAPANGAN+SEP...,Jawa Timur,Nganjuk,Loceret
2,Taman Bibit,"Waung, Kec. Baron, Kabupaten Nganjuk, Jawa Tim...",4.2,https://www.google.com/maps/place/Taman+Bibit/...,Jawa Timur,Nganjuk,Baron
3,Gantangan Guyangan BC Reborn,"CV9H+C25, Guyangan, Kec. Bagor, Kabupaten Ngan...",5.0,https://www.google.com/maps/place/Gantangan+Gu...,Jawa Timur,Nganjuk,Bagor
4,Wisata Gondali View,"7V8P+2J7, Jl. Sumberklampok, Sanan, Macanan, K...",5.0,https://www.google.com/maps/place/Wisata+Gonda...,Jawa Timur,Nganjuk,Loceret
5,Puncak Tapan 11,"6Q9Q+C6C, Unnamed Road, Hutan, Bareng, Sawahan...",4.8,https://www.google.com/maps/place/Puncak+Tapan...,Jawa Timur,Nganjuk,Sawahan

In [32]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Bojonegoro

In [33]:
tmp = taman_bojonegoro.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,LAPANGAN SUKOSEWU,"Jl. Raya Sukosewu No.18, RW.01, Kalicilik Lor,...","4,6",https://www.google.com/maps/place/LAPANGAN+SUK...,Jawa Timur 62185,Kabupaten Bojonegoro,Kec. Sukosewu
1,Wisata Kayangan Api,"Ngembul, Sendangharjo, Kec. Ngasem, Kabupaten ...","4,3",https://www.google.com/maps/place/Wisata+Kayan...,Jawa Timur 62171,Kabupaten Bojonegoro,Kec. Ngasem
3,Yanti Embroidery,"Jl. Tri Tunggal No.12, Karang Pacar, Kec. Bojo...",5,https://www.google.com/maps/place/Yanti+Embroi...,Jawa Timur 62119,Kabupaten Bojonegoro,Kec. Bojonegoro
5,Kwangen Rejo,"RQ6W+FPR, Kumpul Bejo, Leran, Kec. Kalitidu, K...",5,https://www.google.com/maps/place/Kwangen+Rejo...,Jawa Timur,Kabupaten Bojonegoro,Kec. Kalitidu
6,Waduk sumodikaran,"QVP6+M8X, Waduk Gayam, Sawah, Sumodikaran, Kec...","4,6",https://www.google.com/maps/place/Waduk+sumodi...,Jawa Timur 62171,Kabupaten Bojonegoro,Kec. Dander

In [34]:
tmp.drop(tmp.loc[tmp["Kota"] == "Jawa Timur"].index, inplace=True)

In [35]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0      Jawa Timur
1      Jawa Timur
3      Jawa Timur
5      Jawa Timur
6      Jawa Timur
          ...
115    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 89, dtype: category
Categories (1, object): ['Jawa Timur']

In [36]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Tuban"].index, inplace=True)
tmp["Kota"].replace(["Kabupaten Bojonegoro", "Bojonegoro Regency"], "Bojonegoro", inplace=True)
tmp["Kota"].astype("category")

0      Bojonegoro
1      Bojonegoro
3      Bojonegoro
5      Bojonegoro
6      Bojonegoro
          ...
115    Bojonegoro
116    Bojonegoro
117    Bojonegoro
118    Bojonegoro
119    Bojonegoro
Name: Kota, Length: 88, dtype: category
Categories (1, object): ['Bojonegoro']

In [37]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0        Sukosewu
1          Ngasem
3      Bojonegoro
5        Kalitidu
6          Dander
          ...
115    Sugihwaras
116    Bojonegoro
117    Bojonegoro
118    Bojonegoro
119         Sekar
Name: Kecamatan, Length: 88, dtype: category
Categories (19, object): ['Balen', 'Bojonegoro', 'Dander', 'Kalitidu', ..., 'Sumbang', 'Sumberejo',
                          'Temayang', 'Trucuk']

In [38]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,LAPANGAN SUKOSEWU,"Jl. Raya Sukosewu No.18, RW.01, Kalicilik Lor,...",4.6,https://www.google.com/maps/place/LAPANGAN+SUK...,Jawa Timur,Bojonegoro,Sukosewu
1,Wisata Kayangan Api,"Ngembul, Sendangharjo, Kec. Ngasem, Kabupaten ...",4.3,https://www.google.com/maps/place/Wisata+Kayan...,Jawa Timur,Bojonegoro,Ngasem
3,Yanti Embroidery,"Jl. Tri Tunggal No.12, Karang Pacar, Kec. Bojo...",5.0,https://www.google.com/maps/place/Yanti+Embroi...,Jawa Timur,Bojonegoro,Bojonegoro
5,Kwangen Rejo,"RQ6W+FPR, Kumpul Bejo, Leran, Kec. Kalitidu, K...",5.0,https://www.google.com/maps/place/Kwangen+Rejo...,Jawa Timur,Bojonegoro,Kalitidu
6,Waduk sumodikaran,"QVP6+M8X, Waduk Gayam, Sawah, Sumodikaran, Kec...",4.6,https://www.google.com/maps/place/Waduk+sumodi...,Jawa Timur,Bojonegoro,Dander

In [39]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Tuban

In [40]:
tmp = taman_tuban.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Sendang Celeng Bulung Soko Tuban,"WWMW+JH5, Bulung, Nguruan, Kec. Soko, Kabupate...","4,7",https://www.google.com/maps/place/Sendang+Cele...,Jawa Timur 62372,Kabupaten Tuban,Kec. Soko
1,Gamefantasia Tuban,"Bravo Swalayan, Jl. Basuki Rachmad No.64, Kuto...","4,4",https://www.google.com/maps/place/Gamefantasia...,Jawa Timur 62311,Kabupaten Tuban,Kec. Tuban
3,My House,"Gang cemara 1 No.4, Perbon, Kec. Tuban, Kabupa...",5,https://www.google.com/maps/place/My+House/@-6...,Jawa Timur 62311,Kabupaten Tuban,Kec. Tuban
4,Taman Bermain Wire Tuban,"33RG+G65, Dondong, Gedongombo, Kec. Semanding,...","3,7",https://www.google.com/maps/place/Taman+Bermai...,Jawa Timur 62381,Kabupaten Tuban,Kec. Semanding
6,MABES BONSAI TUBAN,"Secang, Ngandong, Kec. Grabagan, Kabupaten Tub...","4,9",https://www.google.com/maps/place/MABES+BONSAI...,Jawa Timur 62371,Kabupaten Tuban,Kec. Grabagan

In [41]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0      Jawa Timur
1      Jawa Timur
3      Jawa Timur
4      Jawa Timur
6      Jawa Timur
          ...
115    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 87, dtype: category
Categories (1, object): ['Jawa Timur']

In [42]:
tmp["Kota"].replace(["Kabupaten Tuban", "Tuban Regency"], "Tuban", inplace=True)
tmp["Kota"].astype("category")

0      Tuban
1      Tuban
3      Tuban
4      Tuban
6      Tuban
       ...
115    Tuban
116    Tuban
117    Tuban
118    Tuban
119    Tuban
Name: Kota, Length: 87, dtype: category
Categories (1, object): ['Tuban']

In [43]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0           Soko
1          Tuban
3          Tuban
4      Semanding
6       Grabagan
         ...
115         Jenu
116        Tuban
117        Tuban
118         Soko
119         Jenu
Name: Kecamatan, Length: 87, dtype: category
Categories (14, object): ['Bancar', 'Grabagan', 'Jenu', 'Kerek', ..., 'Semanding', 'Soko',
                          'Togonongko', 'Tuban']

In [44]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Sendang Celeng Bulung Soko Tuban,"WWMW+JH5, Bulung, Nguruan, Kec. Soko, Kabupate...",4.7,https://www.google.com/maps/place/Sendang+Cele...,Jawa Timur,Tuban,Soko
1,Gamefantasia Tuban,"Bravo Swalayan, Jl. Basuki Rachmad No.64, Kuto...",4.4,https://www.google.com/maps/place/Gamefantasia...,Jawa Timur,Tuban,Tuban
3,My House,"Gang cemara 1 No.4, Perbon, Kec. Tuban, Kabupa...",5.0,https://www.google.com/maps/place/My+House/@-6...,Jawa Timur,Tuban,Tuban
4,Taman Bermain Wire Tuban,"33RG+G65, Dondong, Gedongombo, Kec. Semanding,...",3.7,https://www.google.com/maps/place/Taman+Bermai...,Jawa Timur,Tuban,Semanding
6,MABES BONSAI TUBAN,"Secang, Ngandong, Kec. Grabagan, Kabupaten Tub...",4.9,https://www.google.com/maps/place/MABES+BONSAI...,Jawa Timur,Tuban,Grabagan

In [45]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Kediri

In [46]:
tmp = taman_kediri.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Wisata View 138 Kediri,"Jl. Tembus Lb. Tumpang No.18, Hutan, Kec. Mojo...","4,2",https://www.google.com/maps/place/Wisata+View+...,Jawa Timur 64115,Kabupaten Kediri,Kec. Mojoroto
1,Manisrenggo Park Residence,"5235+8C4, Manisrenggo, Kec. Kota, Kota Kediri,...","4,8",https://www.google.com/maps/place/Manisrenggo+...,Jawa Timur 64129,Kota Kediri,Kec. Kota
2,Arca Totok Kerot,"632C+R46, Jl. Totok Kerot, Bulu Ps., Bulupasar...","4,4",https://www.google.com/maps/place/Arca+Totok+K...,Jawa Timur 64183,Kabupaten Kediri,Kec. Pagu
3,Taman WISATA JF2,"Tunggul sunnah, selopanggung, kec.semen , kab....","4,7",https://www.google.com/maps/place/Taman+WISATA...,Jawa Timur 64161,Kabupaten Kediri,Kec. Semen
4,Oto Park,"Jl. Nasional 22 No.251-273, Ngronggo, Kec. Kot...",4,https://www.google.com/maps/place/Oto+Park/@-7...,Jawa Timur 64129,Kota Kediri,Kec. Kota

In [47]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0      Jawa Timur
1      Jawa Timur
2      Jawa Timur
3      Jawa Timur
4      Jawa Timur
          ...
115    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 99, dtype: category
Categories (1, object): ['Jawa Timur']

In [48]:
tmp["Kota"].replace(["Kabupaten Kediri", "Kediri Regency", "Kota Kediri"], "Kediri", inplace=True)
tmp["Kota"].astype("category")

0      Kediri
1      Kediri
2      Kediri
3      Kediri
4      Kediri
        ...
115    Kediri
116    Kediri
117    Kediri
118    Kediri
119    Kediri
Name: Kota, Length: 99, dtype: category
Categories (1, object): ['Kediri']

In [49]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0      Mojoroto
1          Kota
2          Pagu
3         Semen
4          Kota
         ...
115      Ngasem
116        Kota
117    Mojoroto
118        Kota
119        Kota
Name: Kecamatan, Length: 99, dtype: category
Categories (16, object): ['Banyakan', 'Gurah', 'Kandat', 'Kepung', ..., 'Pesantren', 'Semen', 'Sragi',
                          'Wates']

In [50]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Wisata View 138 Kediri,"Jl. Tembus Lb. Tumpang No.18, Hutan, Kec. Mojo...",4.2,https://www.google.com/maps/place/Wisata+View+...,Jawa Timur,Kediri,Mojoroto
1,Manisrenggo Park Residence,"5235+8C4, Manisrenggo, Kec. Kota, Kota Kediri,...",4.8,https://www.google.com/maps/place/Manisrenggo+...,Jawa Timur,Kediri,Kota
2,Arca Totok Kerot,"632C+R46, Jl. Totok Kerot, Bulu Ps., Bulupasar...",4.4,https://www.google.com/maps/place/Arca+Totok+K...,Jawa Timur,Kediri,Pagu
3,Taman WISATA JF2,"Tunggul sunnah, selopanggung, kec.semen , kab....",4.7,https://www.google.com/maps/place/Taman+WISATA...,Jawa Timur,Kediri,Semen
4,Oto Park,"Jl. Nasional 22 No.251-273, Ngronggo, Kec. Kot...",4.0,https://www.google.com/maps/place/Oto+Park/@-7...,Jawa Timur,Kediri,Kota

In [51]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Pasuruan

In [52]:
tmp = taman_pasuruan.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Mt. Tanggung,"3RF4+W7Q, Pronojiwo, Krajan, Blarang, Kec. Tut...","4,7",https://www.google.com/maps/place/Mt.+Tanggung...,Jawa Timur 67165,Pasuruan,Kec. Tutur
2,Lapangan Milano Nongkojajar,"4R3C+4P7, Pasarbaru, Wonosari, Kec. Tutur, Pas...","4,1",https://www.google.com/maps/place/Lapangan+Mil...,Jawa Timur 67165,Pasuruan,Kec. Tutur
3,HEREX HITS PASURUAN,"7X6R+J3H, Tempuran, Trewung, Kec. Grati, Pasur...",5,https://www.google.com/maps/place/HEREX+HITS+P...,Jawa Timur 67184,Pasuruan,Kec. Grati
4,TAMAN BUNGA IMUT BHAKTI ALAM,"Kemang, Ngembal, Kec. Tutur, Pasuruan, Jawa Ti...","4,7",https://www.google.com/maps/place/TAMAN+BUNGA+...,Jawa Timur 67165,Pasuruan,Kec. Tutur
6,The Lumbung Padi Regency,"9V4R+W93, Sebani, Kec. Gadingrejo, Kota Pasuru...","3,8",https://www.google.com/maps/place/The+Lumbung+...,Jawa Timur 67139,Kota Pasuruan,Kec. Gadingrejo

In [53]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0      Jawa Timur
2      Jawa Timur
3      Jawa Timur
4      Jawa Timur
6      Jawa Timur
          ...
115    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 101, dtype: category
Categories (1, object): ['Jawa Timur']

In [54]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kota SBY"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Mojokerto Regency"].index, inplace=True)
tmp["Kota"].replace(["Kota Pasuruan", "Pasuruan Regency", "Pasuruan City"], "Pasuruan", inplace=True)
tmp["Kota"].astype("category")

0      Pasuruan
2      Pasuruan
3      Pasuruan
4      Pasuruan
6      Pasuruan
         ...
115    Pasuruan
116    Pasuruan
117    Pasuruan
118    Pasuruan
119    Pasuruan
Name: Kota, Length: 99, dtype: category
Categories (1, object): ['Pasuruan']

In [55]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0           Tutur
2           Tutur
3           Grati
4           Tutur
6      Gadingrejo
          ...
115     Purwodadi
116    Gadingrejo
117        Prigen
118        Prigen
119     Purwosari
Name: Kecamatan, Length: 99, dtype: category
Categories (22, object): ['Bangil', 'Beji', 'Bugul Kidul', 'Gadingrejo', ..., 'Sukorejo', 'Tutur',
                          'Winongan', 'Wonorejo']

In [56]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Mt. Tanggung,"3RF4+W7Q, Pronojiwo, Krajan, Blarang, Kec. Tut...",4.7,https://www.google.com/maps/place/Mt.+Tanggung...,Jawa Timur,Pasuruan,Tutur
2,Lapangan Milano Nongkojajar,"4R3C+4P7, Pasarbaru, Wonosari, Kec. Tutur, Pas...",4.1,https://www.google.com/maps/place/Lapangan+Mil...,Jawa Timur,Pasuruan,Tutur
3,HEREX HITS PASURUAN,"7X6R+J3H, Tempuran, Trewung, Kec. Grati, Pasur...",5.0,https://www.google.com/maps/place/HEREX+HITS+P...,Jawa Timur,Pasuruan,Grati
4,TAMAN BUNGA IMUT BHAKTI ALAM,"Kemang, Ngembal, Kec. Tutur, Pasuruan, Jawa Ti...",4.7,https://www.google.com/maps/place/TAMAN+BUNGA+...,Jawa Timur,Pasuruan,Tutur
6,The Lumbung Padi Regency,"9V4R+W93, Sebani, Kec. Gadingrejo, Kota Pasuru...",3.8,https://www.google.com/maps/place/The+Lumbung+...,Jawa Timur,Pasuruan,Gadingrejo

In [57]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman Gresik

In [58]:
tmp = taman_gresik.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Taman Kesehatan GKB,"RJR8+6X9, Setingi, Randuagung, Kec. Gresik, Ka...","4,6",https://www.google.com/maps/place/Taman+Keseha...,Jawa Timur 61121,Kabupaten Gresik,Kec. Gresik
1,Taman Bundaran I Love GKB,"RJX7+V2P, Karanggondang, Yosowilangun, Kec. Gr...","4,6",https://www.google.com/maps/place/Taman+Bundar...,Jawa Timur 61151,Kabupaten Gresik,Kec. Gresik
2,Taman Bawah Jembatan Prambangan,"RJ4G+XFR, Napes, Gulomantung, Kec. Kebomas, Ka...","4,7",https://www.google.com/maps/place/Taman+Bawah+...,Jawa Timur 61124,Kabupaten Gresik,Kec. Kebomas
3,Taman indah Edukasi,"No., Jl. Raya Mutiara No.96, Suci, Kec. Manyar...","4,1",https://www.google.com/maps/place/Taman+indah+...,Jawa Timur 61151,Kabupaten Gresik,Kec. Manyar
4,Telaga Kerobokan,"RJJH+84G, Jl. Sunan Prapen IV, Pedukuhan, Kebo...","4,7",https://www.google.com/maps/place/Telaga+Kerob...,Jawa Timur 61124,Kabupaten Gresik,Kec. Kebomas

In [59]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0     Jawa Timur
1     Jawa Timur
2     Jawa Timur
3     Jawa Timur
4     Jawa Timur
5     Jawa Timur
6     Jawa Timur
7     Jawa Timur
8     Jawa Timur
9     Jawa Timur
10    Jawa Timur
11    Jawa Timur
12    Jawa Timur
13    Jawa Timur
14    Jawa Timur
15    Jawa Timur
16    Jawa Timur
17    Jawa Timur
18    Jawa Timur
19    Jawa Timur
Name: Provinsi, dtype: category
Categories (1, object): ['Jawa Timur']

In [60]:
tmp["Kota"].replace("Kabupaten Gresik", "Gresik", inplace=True)
tmp["Kota"].astype("category")

0     Gresik
1     Gresik
2     Gresik
3     Gresik
4     Gresik
5     Gresik
6     Gresik
7     Gresik
8     Gresik
9     Gresik
10    Gresik
11    Gresik
12    Gresik
13    Gresik
14    Gresik
15    Gresik
16    Gresik
17    Gresik
18    Gresik
19    Gresik
Name: Kota, dtype: category
Categories (1, object): ['Gresik']

In [61]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0      Gresik
1      Gresik
2     Kebomas
3      Manyar
4     Kebomas
5     Kebomas
6      Manyar
7     Kebomas
8      Gresik
9      Gresik
10     Gresik
11    Kebomas
12    Kebomas
13    Kebomas
14    Kebomas
15    Kebomas
16    Kebomas
17     Gresik
18     Gresik
19    Kebomas
Name: Kecamatan, dtype: category
Categories (3, object): ['Gresik', 'Kebomas', 'Manyar']

In [62]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Taman Kesehatan GKB,"RJR8+6X9, Setingi, Randuagung, Kec. Gresik, Ka...",4.6,https://www.google.com/maps/place/Taman+Keseha...,Jawa Timur,Gresik,Gresik
1,Taman Bundaran I Love GKB,"RJX7+V2P, Karanggondang, Yosowilangun, Kec. Gr...",4.6,https://www.google.com/maps/place/Taman+Bundar...,Jawa Timur,Gresik,Gresik
2,Taman Bawah Jembatan Prambangan,"RJ4G+XFR, Napes, Gulomantung, Kec. Kebomas, Ka...",4.7,https://www.google.com/maps/place/Taman+Bawah+...,Jawa Timur,Gresik,Kebomas
3,Taman indah Edukasi,"No., Jl. Raya Mutiara No.96, Suci, Kec. Manyar...",4.1,https://www.google.com/maps/place/Taman+indah+...,Jawa Timur,Gresik,Manyar
4,Telaga Kerobokan,"RJJH+84G, Jl. Sunan Prapen IV, Pedukuhan, Kebo...",4.7,https://www.google.com/maps/place/Telaga+Kerob...,Jawa Timur,Gresik,Kebomas

In [63]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_taman = tmp_taman.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Surabaya

In [64]:
tmp = museum_surabaya.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Monumen Pendidikan,"MMXF+HM9 Universitas Negeri Surabaya, Lidah We...",4.5,https://www.google.com/maps/place/Monumen+Pend...,East Java 60213,Surabaya City,Wiyung
3,Toko Mainan Micky Mouse Pusat Grosir Surabaya,"Pusat Grosir Surabaya, Jalan Surabaya Lantai 4...",5.0,https://www.google.com/maps/place/Toko+Mainan+...,Jawa Timur 60172,Kota SBY,Kec. Bubutan
4,Gedung Parkir Genteng Kali,"PPVV+3FM, Jl. Genteng Kali, RW.11, Genteng, Ke...",4.8,https://www.google.com/maps/place/Gedung+Parki...,Jawa Timur 60275,Kota SBY,Kec. Genteng
5,Universitas Dinamika (STIKOM Surabaya),"Jl. Raya Kedung Baruk No.98, Kedung Baruk, Kec...",4.8,https://www.google.com/maps/place/Universitas+...,Jawa Timur 60298,Kota SBY,Kec. Rungkut
6,Museum Islam Indonesia KH Hasyim Asy'ari Tebui...,"96RM+HV7, Tebuireng Gg. 3, Kwaron, Cukir, Kec....",4.6,https://www.google.com/maps/place/Museum+Islam...,Jawa Timur 61471,Kabupaten Jombang,Kec. Diwek

In [65]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0      Jawa Timur
3      Jawa Timur
4      Jawa Timur
5      Jawa Timur
6      Jawa Timur
          ...
109    Jawa Timur
110    Jawa Timur
111    Jawa Timur
112    Jawa Timur
113    Jawa Timur
Name: Provinsi, Length: 93, dtype: category
Categories (1, object): ['Jawa Timur']

In [66]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Jombang"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Sidoarjo"].index, inplace=True)
tmp["Kota"].replace(["Kota SBY", "Surabaya City"], "Surabaya", inplace=True)
tmp["Kota"].astype("category")

0      Surabaya
3      Surabaya
4      Surabaya
5      Surabaya
7      Surabaya
         ...
109    Surabaya
110    Surabaya
111    Surabaya
112    Surabaya
113    Surabaya
Name: Kota, Length: 89, dtype: category
Categories (1, object): ['Surabaya']

In [67]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0          Wiyung
3         Bubutan
4         Genteng
5         Rungkut
7         Genteng
          ...
109        Gubeng
110    Tambaksari
111       Bubutan
112       Genteng
113       Bubutan
Name: Kecamatan, Length: 89, dtype: category
Categories (24, object): ['Benowo', 'Bubutan', 'Bulak', 'Dukuhpakis', ..., 'Tenggilis Mejoyo',
                          'Wiyung', 'Wonokromo', 'surabayq pusat']

In [68]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

Udah Benar

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Monumen Pendidikan,"MMXF+HM9 Universitas Negeri Surabaya, Lidah We...",4.5,https://www.google.com/maps/place/Monumen+Pend...,Jawa Timur,Surabaya,Wiyung
3,Toko Mainan Micky Mouse Pusat Grosir Surabaya,"Pusat Grosir Surabaya, Jalan Surabaya Lantai 4...",5.0,https://www.google.com/maps/place/Toko+Mainan+...,Jawa Timur,Surabaya,Bubutan
4,Gedung Parkir Genteng Kali,"PPVV+3FM, Jl. Genteng Kali, RW.11, Genteng, Ke...",4.8,https://www.google.com/maps/place/Gedung+Parki...,Jawa Timur,Surabaya,Genteng
5,Universitas Dinamika (STIKOM Surabaya),"Jl. Raya Kedung Baruk No.98, Kedung Baruk, Kec...",4.8,https://www.google.com/maps/place/Universitas+...,Jawa Timur,Surabaya,Rungkut
7,Balai Pemuda Surabaya,"Jl. Gubernur Suryo No.15, Embong Kaliasin, Kec...",4.7,https://www.google.com/maps/place/Balai+Pemuda...,Jawa Timur,Surabaya,Genteng

In [69]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Sidoarjo

In [70]:
tmp = museum_sidoarjo.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Monumen Pancasila Sidoarjo,"HP22+X5W, Jati, Sidoarjo, Sidoarjo Regency, Ea...",4.5,https://www.google.com/maps/place/Monumen+Panc...,East Java 61226,Sidoarjo Regency,Sidoarjo
2,Kuburan Kembar Kedungturi,"JPR3+W98, Medaeng Kulon, Kedungturi, Kec. Tama...",4.0,https://www.google.com/maps/place/Kuburan+Kemb...,Jawa Timur 61257,Kabupaten Sidoarjo,Kec. Taman
3,Makam Mbah H M Nur Ali,"Jalan Pesantren RT 1 RW 1 Kec., Gebang, Sidoar...",3.0,https://www.google.com/maps/place/Makam+Mbah+H...,East Java 61231,Sidoarjo Regency,Sidoarjo
6,Makam Mbah Serebon,"HMGF+H3Q, Kebonagung, Kec. Sukodono, Kabupaten...",5.0,https://www.google.com/maps/place/Makam+Mbah+S...,Jawa Timur 61258,Kabupaten Sidoarjo,Kec. Sukodono
9,Markas RING Bafi Series,"Jl. Gemelina No.34, Payan, Pabean, Kec. Sedati...",4.5,https://www.google.com/maps/place/Markas+RING+...,Jawa Timur 61253,Kabupaten Sidoarjo,Kec. Sedati

In [71]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0     Jawa Timur
2     Jawa Timur
3     Jawa Timur
6     Jawa Timur
9     Jawa Timur
13    Jawa Timur
15    Jawa Timur
18    Jawa Timur
22    Jawa Timur
23    Jawa Timur
24    Jawa Timur
25    Jawa Timur
26    Jawa Timur
27    Jawa Timur
28    Jawa Timur
29    Jawa Timur
30    Jawa Timur
31    Jawa Timur
32    Jawa Timur
33    Jawa Timur
34    Jawa Timur
35    Jawa Timur
36    Jawa Timur
38    Jawa Timur
40    Jawa Timur
41    Jawa Timur
42    Jawa Timur
43    Jawa Timur
44    Jawa Timur
45    Jawa Timur
48    Jawa Timur
49    Jawa Timur
50    Jawa Timur
51    Jawa Timur
52    Jawa Timur
54    Jawa Timur
55    Jawa Timur
57    Jawa Timur
59    Jawa Timur
61    Jawa Timur
62    Jawa Timur
63    Jawa Timur
64    Jawa Timur
65    Jawa Timur
66    Jawa Timur
67    Jawa Timur
Name: Provinsi, dtype: category
Categories (1, object): ['Jawa Timur']

In [72]:
tmp["Kota"].replace(["Kabupaten Sidoarjo", "Sidoarjo Regency"], "Sidoarjo", inplace=True)
tmp["Kota"].astype("category")

0     Sidoarjo
2     Sidoarjo
3     Sidoarjo
6     Sidoarjo
9     Sidoarjo
13    Sidoarjo
15    Sidoarjo
18    Sidoarjo
22    Sidoarjo
23    Sidoarjo
24    Sidoarjo
25    Sidoarjo
26    Sidoarjo
27    Sidoarjo
28    Sidoarjo
29    Sidoarjo
30    Sidoarjo
31    Sidoarjo
32    Sidoarjo
33    Sidoarjo
34    Sidoarjo
35    Sidoarjo
36    Sidoarjo
38    Sidoarjo
40    Sidoarjo
41    Sidoarjo
42    Sidoarjo
43    Sidoarjo
44    Sidoarjo
45    Sidoarjo
48    Sidoarjo
49    Sidoarjo
50    Sidoarjo
51    Sidoarjo
52    Sidoarjo
54    Sidoarjo
55    Sidoarjo
57    Sidoarjo
59    Sidoarjo
61    Sidoarjo
62    Sidoarjo
63    Sidoarjo
64    Sidoarjo
65    Sidoarjo
66    Sidoarjo
67    Sidoarjo
Name: Kota, dtype: category
Categories (1, object): ['Sidoarjo']

In [73]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0         Sidoarjo
2            Taman
3         Sidoarjo
6         Sukodono
9           Sedati
13            Waru
15        Tulangan
18          Sedati
22           Candi
23            Waru
24            Waru
25        Gedangan
26           Jabon
27           Taman
28    Karangpilang
29           Candi
30        Sidoarjo
31        Sidoarjo
32        Sidoarjo
33           Taman
34            Waru
35           Krian
36         Buduran
38          Sedati
40            Waru
41         Buduran
42        Sidoarjo
43            Waru
44        Sidoarjo
45          Sedati
48           Taman
49         Buduran
50          Porong
51        Sidoarjo
52            Waru
54        Sidoarjo
55         Buduran
57          Sedati
59        Sidoarjo
61            Waru
62           Tarik
63         Buduran
64        Gedangan
65           Krian
66        Sidoarjo
67         Buduran
Name: Kecamatan, dtype: category
Categories (14, object): ['Buduran', 'Candi', 'Gedangan', 'Jabon', ..., 'Taman', 'Tarik', 'Tulangan',
                          'Waru']

In [74]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

Udah Benar

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Monumen Pancasila Sidoarjo,"HP22+X5W, Jati, Sidoarjo, Sidoarjo Regency, Ea...",4.5,https://www.google.com/maps/place/Monumen+Panc...,Jawa Timur,Sidoarjo,Sidoarjo
2,Kuburan Kembar Kedungturi,"JPR3+W98, Medaeng Kulon, Kedungturi, Kec. Tama...",4.0,https://www.google.com/maps/place/Kuburan+Kemb...,Jawa Timur,Sidoarjo,Taman
3,Makam Mbah H M Nur Ali,"Jalan Pesantren RT 1 RW 1 Kec., Gebang, Sidoar...",3.0,https://www.google.com/maps/place/Makam+Mbah+H...,Jawa Timur,Sidoarjo,Sidoarjo
6,Makam Mbah Serebon,"HMGF+H3Q, Kebonagung, Kec. Sukodono, Kabupaten...",5.0,https://www.google.com/maps/place/Makam+Mbah+S...,Jawa Timur,Sidoarjo,Sukodono
9,Markas RING Bafi Series,"Jl. Gemelina No.34, Payan, Pabean, Kec. Sedati...",4.5,https://www.google.com/maps/place/Markas+RING+...,Jawa Timur,Sidoarjo,Sedati

In [75]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Mojokerto

In [76]:
tmp = museum_mojokerto.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,WAYANG BEBER SUNGGING PRABANGKARA,"Jl. R.Wijaya 42 Rt 01 Rw01 dusun bangsri, desa...",5.0,https://www.google.com/maps/place/WAYANG+BEBER...,Jawa Timur 61385,Kabupaten Mojokerto,Kec. Ngoro
1,MUSEUM H.O.S. TJOKROAMINOTO,"Jl. Peneleh Gg. VII No.29-31, Peneleh, Kec. Ge...",4.7,https://www.google.com/maps/place/MUSEUM+H.O.S...,Jawa Timur 60274,Kota SBY,Kec. Genteng
4,Della Salon,"FFH8+2GH, Kebogerang, Sumbergirang, Kec. Puri,...",5.0,https://www.google.com/maps/place/Della+Salon/...,Jawa Timur 61363,Kabupaten Mojokerto,Kec. Puri
9,Makam Desa Gayam,"GG62+QPQ, Rw. 2, Gayam, Kec. Bangsal, Kabupate...",3.5,https://www.google.com/maps/place/Makam+Desa+G...,Jawa Timur 61381,Kabupaten Mojokerto,Kec. Bangsal
15,Ex Stasiun Mojosari,"Jl. Duku No.9, Rw. IV, Seduri, Kec. Mojosari, ...",4.0,https://www.google.com/maps/place/Ex+Stasiun+M...,Jawa Timur 61382,Kabupaten Mojokerto,Kec. Mojosari

In [77]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0     Jawa Timur
1     Jawa Timur
4     Jawa Timur
9     Jawa Timur
15    Jawa Timur
16    Jawa Timur
17    Jawa Timur
18    Jawa Timur
20    Jawa Timur
22    Jawa Timur
23    Jawa Timur
24    Jawa Timur
25    Jawa Timur
26    Jawa Timur
27    Jawa Timur
28    Jawa Timur
29    Jawa Timur
30    Jawa Timur
31    Jawa Timur
32    Jawa Timur
33    Jawa Timur
34    Jawa Timur
36    Jawa Timur
37    Jawa Timur
38    Jawa Timur
39    Jawa Timur
40    Jawa Timur
41    Jawa Timur
42    Jawa Timur
43    Jawa Timur
44    Jawa Timur
45    Jawa Timur
46    Jawa Timur
47    Jawa Timur
48    Jawa Timur
50    Jawa Timur
51    Jawa Timur
52    Jawa Timur
53    Jawa Timur
54    Jawa Timur
55    Jawa Timur
56    Jawa Timur
57    Jawa Timur
58    Jawa Timur
59    Jawa Timur
60    Jawa Timur
61    Jawa Timur
62    Jawa Timur
Name: Provinsi, dtype: category
Categories (1, object): ['Jawa Timur']

In [78]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Sidoarjo"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kota SBY"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Surabaya City"].index, inplace=True)
tmp["Kota"].replace(["Kabupaten Mojokerto", "Kota Mojokerto", "Mojokerto Regency"], "Mojokerto", inplace=True)
tmp["Kota"].astype("category")

0     Mojokerto
4     Mojokerto
9     Mojokerto
15    Mojokerto
16    Mojokerto
17    Mojokerto
18    Mojokerto
20    Mojokerto
24    Mojokerto
25    Mojokerto
26    Mojokerto
27    Mojokerto
28    Mojokerto
29    Mojokerto
30    Mojokerto
32    Mojokerto
33    Mojokerto
34    Mojokerto
36    Mojokerto
37    Mojokerto
38    Mojokerto
39    Mojokerto
40    Mojokerto
41    Mojokerto
42    Mojokerto
43    Mojokerto
44    Mojokerto
45    Mojokerto
46    Mojokerto
47    Mojokerto
48    Mojokerto
50    Mojokerto
51    Mojokerto
52    Mojokerto
53    Mojokerto
54    Mojokerto
55    Mojokerto
56    Mojokerto
57    Mojokerto
58    Mojokerto
59    Mojokerto
60    Mojokerto
61    Mojokerto
62    Mojokerto
Name: Kota, dtype: category
Categories (1, object): ['Mojokerto']

In [79]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0              Ngoro
4               Puri
9            Bangsal
15          Mojosari
16          Trowulan
17              Puri
18            Trawas
20              Puri
24            Trawas
25          Trowulan
26          Kutorejo
27            Trawas
28          Mojosari
29          Trowulan
30          Jatirejo
32             Gedek
33          Trowulan
34              Puri
36          Kutorejo
37          Trowulan
38             Ngoro
39           Bangsal
40          Mojosari
41         Mojoanyar
42          Trowulan
43             Pacet
44            Trawas
45          Trowulan
46          Trowulan
47          Trowulan
48              Puri
50             Sooko
51          Jatirejo
52             Sooko
53           Dlanggu
54          Trowulan
55          Trowulan
56             Ngoro
57            Trawas
58             Ngoro
59          Trowulan
60         Mojoanyar
61    Prajurit Kulon
62          Trowulan
Name: Kecamatan, dtype: category
Categories (14, object): ['Bangsal', 'Dlanggu', 'Gedek', 'Jatirejo', ..., 'Puri', 'Sooko', 'Trawas',
                          'Trowulan']

In [80]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

Udah Benar

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,WAYANG BEBER SUNGGING PRABANGKARA,"Jl. R.Wijaya 42 Rt 01 Rw01 dusun bangsri, desa...",5.0,https://www.google.com/maps/place/WAYANG+BEBER...,Jawa Timur,Mojokerto,Ngoro
4,Della Salon,"FFH8+2GH, Kebogerang, Sumbergirang, Kec. Puri,...",5.0,https://www.google.com/maps/place/Della+Salon/...,Jawa Timur,Mojokerto,Puri
9,Makam Desa Gayam,"GG62+QPQ, Rw. 2, Gayam, Kec. Bangsal, Kabupate...",3.5,https://www.google.com/maps/place/Makam+Desa+G...,Jawa Timur,Mojokerto,Bangsal
15,Ex Stasiun Mojosari,"Jl. Duku No.9, Rw. IV, Seduri, Kec. Mojosari, ...",4.0,https://www.google.com/maps/place/Ex+Stasiun+M...,Jawa Timur,Mojokerto,Mojosari
16,Balai Dusun Jatisumber - Trowulan,"Dusun Jatisumber, RT.04/RW.01, Prayon, Watesum...",4.6,https://www.google.com/maps/place/Balai+Dusun+...,Jawa Timur,Mojokerto,Trowulan

In [81]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Jombang

In [82]:
tmp = museum_jombang.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
2,CKS (Cangkru'an kopi seduluran),"Unnamed Road, Sumber Mulyo, Sumbermulyo, Kec. ...",5,https://www.google.com/maps/place/CKS+(Cangkru...,Jawa Timur 61419,Kabupaten Jombang,Kec. Jogoroto
3,Tugu Patung Sapi,"H6WM+XPG, Karang Anom, Karang Pakis, Kec. Kabu...","4,4",https://www.google.com/maps/place/Tugu+Patung+...,Jawa Timur 61455,Kabupaten Jombang,Kec. Kabuh
4,SKiN Chapter Jombang 《Jendro》,"G6M7+PPR, Kleco, Tanggungkramat, Kec. Ploso, K...",5,https://www.google.com/maps/place/SKiN+Chapter...,Jawa Timur 61453,Kabupaten Jombang,Kec. Ploso
7,Graveyard,"F64F+WW7, Pulo Lor, Kec. Jombang, Kabupaten Jo...",5,https://www.google.com/maps/place/Graveyard/@-...,Jawa Timur,Kabupaten Jombang,Kec. Jombang
8,Mbah Guru / H Soen SAG,"97V9+57W, Tawar, Grogol, Kec. Diwek, Kabupaten...","4,3",https://www.google.com/maps/place/Mbah+Guru+%2...,Jawa Timur 61471,Kabupaten Jombang,Kec. Diwek

In [83]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

2     Jawa Timur
3     Jawa Timur
4     Jawa Timur
7     Jawa Timur
8     Jawa Timur
         ...
85    Jawa Timur
87    Jawa Timur
88    Jawa Timur
89    Jawa Timur
90    Jawa Timur
Name: Provinsi, Length: 61, dtype: category
Categories (1, object): ['Jawa Timur']

In [84]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kota Kediri"].index, inplace=True)
tmp["Kota"].replace(["Kabupaten Jombang", "Kab. Jombang", "Jombang Regency"], "Jombang", inplace=True)
tmp["Kota"].astype("category")

2     Jombang
3     Jombang
4     Jombang
7     Jombang
8     Jombang
10    Jombang
11    Jombang
12    Jombang
13    Jombang
14    Jombang
16    Jombang
19    Jombang
20    Jombang
22    Jombang
23    Jombang
25    Jombang
26    Jombang
27    Jombang
28    Jombang
30    Jombang
32    Jombang
34    Jombang
35    Jombang
36    Jombang
37    Jombang
38    Jombang
40    Jombang
43    Jombang
44    Jombang
45    Jombang
46    Jombang
47    Jombang
48    Jombang
52    Jombang
55    Jombang
57    Jombang
58    Jombang
59    Jombang
60    Jombang
61    Jombang
63    Jombang
64    Jombang
65    Jombang
68    Jombang
69    Jombang
71    Jombang
72    Jombang
73    Jombang
75    Jombang
77    Jombang
78    Jombang
79    Jombang
80    Jombang
81    Jombang
84    Jombang
85    Jombang
87    Jombang
88    Jombang
89    Jombang
90    Jombang
Name: Kota, dtype: category
Categories (1, object): ['Jombang']

In [85]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

2              Jogoroto
3                 Kabuh
4                 Ploso
7               Jombang
8                 Diwek
10                Ngoro
11              Jombang
12                Kabuh
13                 Gudo
14                Diwek
16             Sumobito
19                 Kudu
20              Jombang
22             Kesamben
23           Peterongan
25               Bareng
26              Jombang
27           Peterongan
28             Sumobito
30             Plandaan
32              Jombang
34             Jogoroto
35            Mojowarno
36            Tembelang
37                Kabuh
38                Diwek
40                 Kudu
43             Jogoroto
44                Ngoro
45              Jombang
46              Jombang
47              Jombang
48            Mojowarno
52              Jombang
55            Mojowarno
57              Jombang
58    Bandarkedungmulyo
59    Bandarkedungmulyo
60                Ngoro
61                 Gudo
63                Ngoro
64                Ngoro
65            Tembelang
68                Diwek
69             Plandaan
71            Tembelang
72                Diwek
73              Jombang
75                Ploso
77           Peterongan
78                Ploso
79              Jombang
80              Jombang
81                Ngoro
84                Diwek
85                Diwek
87               Bareng
88              Jombang
89                 Gudo
90                Diwek
Name: Kecamatan, dtype: category
Categories (16, object): ['Bandarkedungmulyo', 'Bareng', 'Diwek', 'Gudo', ..., 'Plandaan', 'Ploso', 'Sumobito',
                          'Tembelang']

In [86]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
2,CKS (Cangkru'an kopi seduluran),"Unnamed Road, Sumber Mulyo, Sumbermulyo, Kec. ...",5.0,https://www.google.com/maps/place/CKS+(Cangkru...,Jawa Timur,Jombang,Jogoroto
3,Tugu Patung Sapi,"H6WM+XPG, Karang Anom, Karang Pakis, Kec. Kabu...",4.4,https://www.google.com/maps/place/Tugu+Patung+...,Jawa Timur,Jombang,Kabuh
4,SKiN Chapter Jombang 《Jendro》,"G6M7+PPR, Kleco, Tanggungkramat, Kec. Ploso, K...",5.0,https://www.google.com/maps/place/SKiN+Chapter...,Jawa Timur,Jombang,Ploso
7,Graveyard,"F64F+WW7, Pulo Lor, Kec. Jombang, Kabupaten Jo...",5.0,https://www.google.com/maps/place/Graveyard/@-...,Jawa Timur,Jombang,Jombang
8,Mbah Guru / H Soen SAG,"97V9+57W, Tawar, Grogol, Kec. Diwek, Kabupaten...",4.3,https://www.google.com/maps/place/Mbah+Guru+%2...,Jawa Timur,Jombang,Diwek

In [87]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Nganjuk

In [88]:
tmp = museum_nganjuk.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Monumen Adipura Nganjuk,"9WW4+PXM, Nganjuk, Ganung Kidul, Kec. Nganjuk,...",3,https://www.google.com/maps/place/Monumen+Adip...,Jawa Timur 64419,Kabupaten Nganjuk,Kec. Nganjuk
1,Museum Radio Indonesia,"RT.5/RW.4, Ngrombot, Selorejo, Kec. Bagor, Kab...",5,https://www.google.com/maps/place/Museum+Radio...,Jawa Timur 64461,Kabupaten Nganjuk,Kec. Bagor
2,Museum Dr. Soetomo Nganjuk,"8VMP+W5P, Sono, Ngepeh, Kec. Loceret, Kabupate...","4,2",https://www.google.com/maps/place/Museum+Dr.+S...,Jawa Timur 64471,Kabupaten Nganjuk,Kec. Loceret
3,Museum Anjuk Ladang,"Terminal Bus anjuk ladang, Jalan Gatot Subroto...","4,3",https://www.google.com/maps/place/Museum+Anjuk...,Jawa Timur 64411,Kabupaten Nganjuk,Kec. Nganjuk

In [89]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].astype("category")

0    Jawa Timur
1    Jawa Timur
2    Jawa Timur
3    Jawa Timur
Name: Provinsi, dtype: category
Categories (1, object): ['Jawa Timur']

In [90]:
tmp["Kota"].replace("Kabupaten Nganjuk", "Nganjuk", inplace=True)
tmp["Kota"].astype("category")

0    Nganjuk
1    Nganjuk
2    Nganjuk
3    Nganjuk
Name: Kota, dtype: category
Categories (1, object): ['Nganjuk']

In [91]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0    Nganjuk
1      Bagor
2    Loceret
3    Nganjuk
Name: Kecamatan, dtype: category
Categories (3, object): ['Bagor', 'Loceret', 'Nganjuk']

In [92]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Monumen Adipura Nganjuk,"9WW4+PXM, Nganjuk, Ganung Kidul, Kec. Nganjuk,...",3.0,https://www.google.com/maps/place/Monumen+Adip...,Jawa Timur,Nganjuk,Nganjuk
1,Museum Radio Indonesia,"RT.5/RW.4, Ngrombot, Selorejo, Kec. Bagor, Kab...",5.0,https://www.google.com/maps/place/Museum+Radio...,Jawa Timur,Nganjuk,Bagor
2,Museum Dr. Soetomo Nganjuk,"8VMP+W5P, Sono, Ngepeh, Kec. Loceret, Kabupate...",4.2,https://www.google.com/maps/place/Museum+Dr.+S...,Jawa Timur,Nganjuk,Loceret
3,Museum Anjuk Ladang,"Terminal Bus anjuk ladang, Jalan Gatot Subroto...",4.3,https://www.google.com/maps/place/Museum+Anjuk...,Jawa Timur,Nganjuk,Nganjuk

In [93]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Bojonegoro

In [94]:
tmp = museum_bojonegoro.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
2,Serba Murah,"RW8W+X3M, Bahoro, Sobontoro, Kec. Balen, Kabup...",5,https://www.google.com/maps/place/Serba+Murah/...,Jawa Timur 62182,Kabupaten Bojonegoro,Kec. Balen
4,Taman Pejambon,"R22C+MPX, Jl. RA. Kartini, Pejambon, Kec. Sumb...","4,4",https://www.google.com/maps/place/Taman+Pejamb...,Jawa Timur 62191,Kabupaten Bojonegoro,Kec. Sumberejo
5,Air Terjun Kedunggupit,"HQ8H+H77, Dusun Gayam Desa Klino Kec. Sekar Ka...","4,4",https://www.google.com/maps/place/Air+Terjun+K...,Jawa Timur 62167,Kabupaten Bojonegoro,Kec. Sekar
6,Air Terjun Maor,"JVV2+73M, Clebung, Bubulan, Area Hutan, Clebun...","4,4",https://www.google.com/maps/place/Air+Terjun+M...,Jawa Timur 62172,Kabupaten Bojonegoro,Bojonegoro
7,Balai Desa Sengon,"PP58+MHW, Bondol, Ngambon, Bondol, Bojonegoro,...",5,https://www.google.com/maps/place/Balai+Desa+S...,Jawa Timur 62167,Kabupaten Bojonegoro,Bojonegoro

In [95]:
tmp.drop(tmp.loc[tmp["Provinsi"] == "Kabupaten Bojonegoro"].index, inplace=True)

In [96]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp.drop(tmp.loc[tmp["Provinsi"] == "Jawa Tengah"].index, inplace=True)
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

2      Jawa Timur
4      Jawa Timur
5      Jawa Timur
6      Jawa Timur
7      Jawa Timur
          ...
114    Jawa Timur
116    Jawa Timur
117    Jawa Timur
118    Jawa Timur
119    Jawa Timur
Name: Provinsi, Length: 81, dtype: category
Categories (1, object): ['Jawa Timur']

In [97]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Tuban"].index, inplace=True)
tmp["Kota"].replace(["Kabupaten Bojonegoro", "Bojonegoro Regency"], "Bojonegoro", inplace=True)
tmp["Kota"].astype("category")

2      Bojonegoro
4      Bojonegoro
5      Bojonegoro
6      Bojonegoro
7      Bojonegoro
          ...
114    Bojonegoro
116    Bojonegoro
117    Bojonegoro
118    Bojonegoro
119    Bojonegoro
Name: Kota, Length: 80, dtype: category
Categories (1, object): ['Bojonegoro']

In [98]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

2           Balen
4       Sumberejo
5           Sekar
6      Bojonegoro
7      Bojonegoro
          ...
114       Baureno
116       Kedewan
117    Bojonegoro
118       Kedewan
119      Kalitidu
Name: Kecamatan, Length: 80, dtype: category
Categories (26, object): ['Balen', 'Baureno', 'Bojonegoro', 'Bubulan', ..., 'Sumberejo',
                          'Tambakrejo', 'Temayang', 'Trucuk']

In [99]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
2,Serba Murah,"RW8W+X3M, Bahoro, Sobontoro, Kec. Balen, Kabup...",5.0,https://www.google.com/maps/place/Serba+Murah/...,Jawa Timur,Bojonegoro,Balen
4,Taman Pejambon,"R22C+MPX, Jl. RA. Kartini, Pejambon, Kec. Sumb...",4.4,https://www.google.com/maps/place/Taman+Pejamb...,Jawa Timur,Bojonegoro,Sumberejo
5,Air Terjun Kedunggupit,"HQ8H+H77, Dusun Gayam Desa Klino Kec. Sekar Ka...",4.4,https://www.google.com/maps/place/Air+Terjun+K...,Jawa Timur,Bojonegoro,Sekar
6,Air Terjun Maor,"JVV2+73M, Clebung, Bubulan, Area Hutan, Clebun...",4.4,https://www.google.com/maps/place/Air+Terjun+M...,Jawa Timur,Bojonegoro,Bojonegoro
7,Balai Desa Sengon,"PP58+MHW, Bondol, Ngambon, Bondol, Bojonegoro,...",5.0,https://www.google.com/maps/place/Balai+Desa+S...,Jawa Timur,Bojonegoro,Bojonegoro

In [100]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Tuban

In [101]:
tmp = museum_tuban.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Persarean Bah Tundung Musoh,"4433+FWJ, Pojuna, Tasikmadu, Kec. Palang, Kabu...",5,https://www.google.com/maps/place/Persarean+Ba...,Jawa Timur 62391,Kabupaten Tuban,Kec. Palang
2,Makam Mbah Ronggo,"4342+5M7, Ronggomulyo, Kec. Tuban, Kabupaten T...",5,https://www.google.com/maps/place/Makam+Mbah+R...,Jawa Timur 62313,Kabupaten Tuban,Kec. Tuban
3,Keramat Dopyak Bangilan,"Jl. St., Bangilan, Kec. Bangilan, Kabupaten Tu...","4,2",https://www.google.com/maps/place/Keramat+Dopy...,Jawa Timur 62364,Kabupaten Tuban,Kec. Bangilan
4,Stasiun Sembung,"XQ3M+JPF, Krajan, Sembung, Kec. Parengan, Kabu...",4,https://www.google.com/maps/place/Stasiun+Semb...,Jawa Timur 62366,Kabupaten Tuban,Kec. Parengan
5,PAGUYUBAN PERKUTUT LOKAL ALAM BUMI RONGGOLAWE ...,"4V8H+FM4, Gendong, Margorejo, Kec. Kerek, Kabu...",5,https://www.google.com/maps/place/PAGUYUBAN+PE...,Jawa Timur 62356,Kabupaten Tuban,Kec. Kerek

In [102]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].astype("category")

0     Jawa Timur
2     Jawa Timur
3     Jawa Timur
4     Jawa Timur
5     Jawa Timur
6     Jawa Timur
7     Jawa Timur
8     Jawa Timur
9     Jawa Timur
10    Jawa Timur
Name: Provinsi, dtype: category
Categories (1, object): ['Jawa Timur']

In [103]:
tmp["Kota"].replace("Kabupaten Tuban", "Tuban", inplace=True)
tmp["Kota"].astype("category")

0     Tuban
2     Tuban
3     Tuban
4     Tuban
5     Tuban
6     Tuban
7     Tuban
8     Tuban
9     Tuban
10    Tuban
Name: Kota, dtype: category
Categories (1, object): ['Tuban']

In [104]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0        Palang
2         Tuban
3      Bangilan
4      Parengan
5         Kerek
6         Tuban
7         Tuban
8          Jenu
9     Semanding
10        Tuban
Name: Kecamatan, dtype: category
Categories (7, object): ['Bangilan', 'Jenu', 'Kerek', 'Palang', 'Parengan', 'Semanding', 'Tuban']

In [105]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Persarean Bah Tundung Musoh,"4433+FWJ, Pojuna, Tasikmadu, Kec. Palang, Kabu...",5.0,https://www.google.com/maps/place/Persarean+Ba...,Jawa Timur,Tuban,Palang
2,Makam Mbah Ronggo,"4342+5M7, Ronggomulyo, Kec. Tuban, Kabupaten T...",5.0,https://www.google.com/maps/place/Makam+Mbah+R...,Jawa Timur,Tuban,Tuban
3,Keramat Dopyak Bangilan,"Jl. St., Bangilan, Kec. Bangilan, Kabupaten Tu...",4.2,https://www.google.com/maps/place/Keramat+Dopy...,Jawa Timur,Tuban,Bangilan
4,Stasiun Sembung,"XQ3M+JPF, Krajan, Sembung, Kec. Parengan, Kabu...",4.0,https://www.google.com/maps/place/Stasiun+Semb...,Jawa Timur,Tuban,Parengan
5,PAGUYUBAN PERKUTUT LOKAL ALAM BUMI RONGGOLAWE ...,"4V8H+FM4, Gendong, Margorejo, Kec. Kerek, Kabu...",5.0,https://www.google.com/maps/place/PAGUYUBAN+PE...,Jawa Timur,Tuban,Kerek

In [106]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Kediri

In [107]:
tmp = museum_kediri.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
5,Situs Ringin Sirah - Legenda Kota Kediri,"52J9+XMJ, Dandangan, Kec. Kota, Kabupaten Kedi...",5,https://www.google.com/maps/place/Situs+Ringin...,Jawa Timur 64129,Kabupaten Kediri,Kec. Kota
7,Tanteri Museum,"Pejaten, Kec. Kediri, Kabupaten Tabanan, Bali ...","4,5",https://www.google.com/maps/place/Tanteri+Muse...,Bali 82121,Kabupaten Tabanan,Kec. Kediri
8,Kediri Town Square,"Jl. Hasanudin No.2, Balowerti, Kec. Kota, Kota...","4,4",https://www.google.com/maps/place/Kediri+Town+...,Jawa Timur 64129,Kota Kediri,Kec. Kota
9,Petirtaan Tirto Kamandanu,"Menang, Kec. Pagu, Kabupaten Kediri, Jawa Timu...","4,4",https://www.google.com/maps/place/Petirtaan+Ti...,Jawa Timur 64183,Kabupaten Kediri,Kec. Pagu
10,"Dinas Kebudayaan, Pariwisata, Kepemudaan dan O...","Jl. KDP Slamet No.33, Mojoroto, Kec. Mojoroto,...","3,9",https://www.google.com/maps/place/Dinas+Kebuda...,Jawa Timur 64114,Kota Kediri,Kec. Mojoroto

In [108]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp.drop(tmp.loc[tmp["Provinsi"] != "Jawa Timur"].index, inplace=True)
tmp["Provinsi"].astype("category")

5     Jawa Timur
8     Jawa Timur
9     Jawa Timur
10    Jawa Timur
11    Jawa Timur
12    Jawa Timur
13    Jawa Timur
14    Jawa Timur
16    Jawa Timur
17    Jawa Timur
18    Jawa Timur
19    Jawa Timur
20    Jawa Timur
21    Jawa Timur
22    Jawa Timur
23    Jawa Timur
24    Jawa Timur
25    Jawa Timur
26    Jawa Timur
27    Jawa Timur
28    Jawa Timur
29    Jawa Timur
30    Jawa Timur
31    Jawa Timur
32    Jawa Timur
33    Jawa Timur
34    Jawa Timur
35    Jawa Timur
36    Jawa Timur
37    Jawa Timur
38    Jawa Timur
39    Jawa Timur
40    Jawa Timur
41    Jawa Timur
42    Jawa Timur
43    Jawa Timur
44    Jawa Timur
45    Jawa Timur
46    Jawa Timur
47    Jawa Timur
48    Jawa Timur
50    Jawa Timur
51    Jawa Timur
52    Jawa Timur
Name: Provinsi, dtype: category
Categories (1, object): ['Jawa Timur']

In [109]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Mojokerto"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Nganjuk"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Tulungagung"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kota Batu"].index, inplace=True)
tmp["Kota"].replace(["Kabupaten Kediri", "Kota Kediri"], "Kediri", inplace=True)
tmp["Kota"].astype("category")

5     Kediri
8     Kediri
9     Kediri
10    Kediri
11    Kediri
12    Kediri
13    Kediri
14    Kediri
16    Kediri
17    Kediri
18    Kediri
19    Kediri
20    Kediri
21    Kediri
22    Kediri
25    Kediri
26    Kediri
27    Kediri
29    Kediri
30    Kediri
31    Kediri
32    Kediri
33    Kediri
36    Kediri
37    Kediri
38    Kediri
39    Kediri
40    Kediri
41    Kediri
42    Kediri
43    Kediri
44    Kediri
45    Kediri
46    Kediri
47    Kediri
48    Kediri
50    Kediri
51    Kediri
52    Kediri
Name: Kota, dtype: category
Categories (1, object): ['Kediri']

In [110]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

5            Kota
8            Kota
9            Pagu
10       Mojoroto
11         Kediri
12      Purwoasri
13    Gampengrejo
14        Ngancar
16       Plemahan
17           Kota
18       Mojoroto
19       Mojoroto
20     Ngadiluwih
21         Kepung
22       Mojoroto
25          Badas
26           Kota
27           Kota
29          Puncu
30         Ngasem
31          Wates
32           Kota
33       Mojoroto
36       Mojoroto
37           Kota
38    Plosoklaten
39          Wates
40         Ngasem
41    Gampengrejo
42    Gampengrejo
43          Semen
44           Pare
45         Ngasem
46         Ngasem
47         Ngasem
48           Mojo
50         Ngasem
51       Mojoroto
52           Kota
Name: Kecamatan, dtype: category
Categories (18, object): ['Badas', 'Gampengrejo', 'Kediri', 'Kepung', ..., 'Puncu', 'Purwoasri',
                          'Semen', 'Wates']

In [111]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
5,Situs Ringin Sirah - Legenda Kota Kediri,"52J9+XMJ, Dandangan, Kec. Kota, Kabupaten Kedi...",5.0,https://www.google.com/maps/place/Situs+Ringin...,Jawa Timur,Kediri,Kota
8,Kediri Town Square,"Jl. Hasanudin No.2, Balowerti, Kec. Kota, Kota...",4.4,https://www.google.com/maps/place/Kediri+Town+...,Jawa Timur,Kediri,Kota
9,Petirtaan Tirto Kamandanu,"Menang, Kec. Pagu, Kabupaten Kediri, Jawa Timu...",4.4,https://www.google.com/maps/place/Petirtaan+Ti...,Jawa Timur,Kediri,Pagu
10,"Dinas Kebudayaan, Pariwisata, Kepemudaan dan O...","Jl. KDP Slamet No.33, Mojoroto, Kec. Mojoroto,...",3.9,https://www.google.com/maps/place/Dinas+Kebuda...,Jawa Timur,Kediri,Mojoroto
11,Air Terjun Dolo,"4RHP+R4W, Dusun Besuki, Desa Jugo, Kecamatan M...",4.4,https://www.google.com/maps/place/Air+Terjun+D...,Jawa Timur,Kediri,Kediri

In [112]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Pasuruan

In [113]:
tmp = museum_pasuruan.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Contack Szoephr Oyx,"8MRP+M3C, Gg damai lingk, Plintahan, kasri, Ke...",5,https://www.google.com/maps/place/Contack+Szoe...,Jawa Timur 67156,Pasuruan,Kec. Pandaan
1,DHIDIT ADVENTUR,"Jl. Raya Bogem Cengkeh, Barsari, Gambiran, Kec...","3,9",https://www.google.com/maps/place/DHIDIT+ADVEN...,Jawa Timur 67157,Pasuruan,Kec. Prigen
3,Pendopo,"Jl. Raya Winongan Lor No.18, Sentul, Winongan ...",4,https://www.google.com/maps/place/Pendopo/@-7....,Jawa Timur 67182,Pasuruan,Kec. Winongan
5,Museum Mpu Tantular,"HP89+FX2, Jl. Raya Buduran - Jembatan Layang, ...","4,4",https://www.google.com/maps/place/Museum+Mpu+T...,Jawa Timur 61252,Kabupaten Sidoarjo,Kec. Buduran
6,Monumen Tugu Pahlawan dan Museum Sepuluh Nopem...,"Jl. Pahlawan, Alun-alun Contong, Kec. Bubutan,...","4,7",https://www.google.com/maps/place/Monumen+Tugu...,Jawa Timur 60174,Kota SBY,Kec. Bubutan

In [114]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].astype("category")

0     Jawa Timur
1     Jawa Timur
3     Jawa Timur
5     Jawa Timur
6     Jawa Timur
7     Jawa Timur
8     Jawa Timur
9     Jawa Timur
11    Jawa Timur
12    Jawa Timur
13    Jawa Timur
14    Jawa Timur
16    Jawa Timur
17    Jawa Timur
19    Jawa Timur
20    Jawa Timur
21    Jawa Timur
22    Jawa Timur
23    Jawa Timur
25    Jawa Timur
26    Jawa Timur
28    Jawa Timur
29    Jawa Timur
30    Jawa Timur
Name: Provinsi, dtype: category
Categories (1, object): ['Jawa Timur']

In [115]:
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Mojokerto"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kabupaten Sidoarjo"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kota Batu"].index, inplace=True)
tmp.drop(tmp.loc[tmp["Kota"] == "Kota SBY"].index, inplace=True)
tmp["Kota"].replace("Kota Pasuruan", "Pasuruan", inplace=True)
tmp["Kota"].astype("category")

0     Pasuruan
1     Pasuruan
3     Pasuruan
7     Pasuruan
8     Pasuruan
9     Pasuruan
13    Pasuruan
14    Pasuruan
16    Pasuruan
17    Pasuruan
19    Pasuruan
20    Pasuruan
21    Pasuruan
22    Pasuruan
23    Pasuruan
25    Pasuruan
26    Pasuruan
28    Pasuruan
29    Pasuruan
30    Pasuruan
Name: Kota, dtype: category
Categories (1, object): ['Pasuruan']

In [116]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0          Pandaan
1           Prigen
3         Winongan
7        Purwosari
8            Grati
9           Prigen
13         Pandaan
14    Panggungrejo
16       Purwodadi
17          Prigen
19       Purworejo
20       Purwosari
21            Beji
22          Bangil
23           Grati
25          Kraton
26          Rejoso
28        Sukorejo
29          Gempol
30         Pandaan
Name: Kecamatan, dtype: category
Categories (14, object): ['Bangil', 'Beji', 'Gempol', 'Grati', ..., 'Purwosari', 'Rejoso', 'Sukorejo',
                          'Winongan']

In [117]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Contack Szoephr Oyx,"8MRP+M3C, Gg damai lingk, Plintahan, kasri, Ke...",5.0,https://www.google.com/maps/place/Contack+Szoe...,Jawa Timur,Pasuruan,Pandaan
1,DHIDIT ADVENTUR,"Jl. Raya Bogem Cengkeh, Barsari, Gambiran, Kec...",3.9,https://www.google.com/maps/place/DHIDIT+ADVEN...,Jawa Timur,Pasuruan,Prigen
3,Pendopo,"Jl. Raya Winongan Lor No.18, Sentul, Winongan ...",4.0,https://www.google.com/maps/place/Pendopo/@-7....,Jawa Timur,Pasuruan,Winongan
7,Kebun Pak Budi,"6MCR+Q5X, Sekar Mojo, Kec. Purwosari, Pasuruan...",4.1,https://www.google.com/maps/place/Kebun+Pak+Bu...,Jawa Timur,Pasuruan,Purwosari
8,Kima Kolatmar,"Jl. Raya Pantura No.9, Bandungan, Gejug Jati, ...",4.3,https://www.google.com/maps/place/Kima+Kolatma...,Jawa Timur,Pasuruan,Grati

In [118]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Museum Gresik

In [119]:
tmp = museum_gresik.copy()
tmp.drop(columns = ["id", "Keyword", "Website", "Plus_Code", "Reviews"], inplace=True)
tmp.dropna(subset = ["Name", "Address", "Rating"], inplace=True)
tmp["Provinsi"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][0].strip())
tmp["Kota"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][1].strip())
tmp["Kecamatan"] = tmp["Address"].apply(lambda data: data.split(",")[::-1][2].strip())
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Makam keluarga H Ilyas Gresik,"XH3C+HCR, Unnamed Road, Area Sawah/Kebun, Bung...",5,https://www.google.com/maps/place/Makam+keluar...,East Java 61152,Gresik Regency,Bungah
2,Pos Hendrosari,"QH3M+G2W, Hendrosalam, Hendrosari, Kec. Mengan...",5,https://www.google.com/maps/place/Pos+Hendrosa...,Jawa Timur 61174,Kabupaten Gresik,Kec. Menganti
5,Gardoe ANIEM te Grissee,"RMW4+6FW, Jl. Raden Santri, Bedilan, Kebungson...",5,https://www.google.com/maps/place/Gardoe+ANIEM...,Jawa Timur 61114,Kabupaten Gresik,Kec. Gresik
9,Makam Eyang Kidang Kuning,"VJ34+Q29, Suci, Kec. Manyar, Kabupaten Gresik,...",5,https://www.google.com/maps/place/Makam+Eyang+...,Jawa Timur 61151,Kabupaten Gresik,Kec. Manyar
11,Gapura KARANG PLOSO,"Dsn karang ploso rt 10, Karangploso, Klampok, ...","4,1",https://www.google.com/maps/place/Gapura+KARAN...,Jawa Timur 61172,Kabupaten Gresik,Kec. Benjeng

In [120]:
tmp["Provinsi"] = tmp["Provinsi"].apply(lambda data: " ".join(data.split()[:2]))
tmp["Provinsi"].replace("East Java", "Jawa Timur", inplace=True)
tmp["Provinsi"].astype("category")

0     Jawa Timur
2     Jawa Timur
5     Jawa Timur
9     Jawa Timur
11    Jawa Timur
12    Jawa Timur
13    Jawa Timur
14    Jawa Timur
16    Jawa Timur
17    Jawa Timur
18    Jawa Timur
19    Jawa Timur
20    Jawa Timur
21    Jawa Timur
22    Jawa Timur
23    Jawa Timur
26    Jawa Timur
28    Jawa Timur
29    Jawa Timur
30    Jawa Timur
31    Jawa Timur
35    Jawa Timur
36    Jawa Timur
37    Jawa Timur
39    Jawa Timur
40    Jawa Timur
42    Jawa Timur
43    Jawa Timur
44    Jawa Timur
45    Jawa Timur
50    Jawa Timur
51    Jawa Timur
53    Jawa Timur
54    Jawa Timur
55    Jawa Timur
56    Jawa Timur
57    Jawa Timur
58    Jawa Timur
59    Jawa Timur
60    Jawa Timur
61    Jawa Timur
63    Jawa Timur
65    Jawa Timur
67    Jawa Timur
68    Jawa Timur
69    Jawa Timur
70    Jawa Timur
Name: Provinsi, dtype: category
Categories (1, object): ['Jawa Timur']

In [121]:
tmp["Kota"].replace(["Kabupaten Gresik", "Gresik Regency"], "Gresik", inplace=True)
tmp["Kota"].astype("category")

0     Gresik
2     Gresik
5     Gresik
9     Gresik
11    Gresik
12    Gresik
13    Gresik
14    Gresik
16    Gresik
17    Gresik
18    Gresik
19    Gresik
20    Gresik
21    Gresik
22    Gresik
23    Gresik
26    Gresik
28    Gresik
29    Gresik
30    Gresik
31    Gresik
35    Gresik
36    Gresik
37    Gresik
39    Gresik
40    Gresik
42    Gresik
43    Gresik
44    Gresik
45    Gresik
50    Gresik
51    Gresik
53    Gresik
54    Gresik
55    Gresik
56    Gresik
57    Gresik
58    Gresik
59    Gresik
60    Gresik
61    Gresik
63    Gresik
65    Gresik
67    Gresik
68    Gresik
69    Gresik
70    Gresik
Name: Kota, dtype: category
Categories (1, object): ['Gresik']

In [122]:
tmp["Kecamatan"] = tmp["Kecamatan"].apply(lambda data: " ".join(data.split()[1:]) if (len(data.split())>1 and "Kec" in data.split()[0]) else data)
tmp["Kecamatan"].astype("category")

0          Bungah
2        Menganti
5          Gresik
9          Manyar
11        Benjeng
12         Manyar
13    Wringinanom
14       Menganti
16         Gresik
17       Kedamean
18         Gresik
19        Kebomas
20         Bungah
21         Gresik
22       Menganti
23          Cerme
26         Gresik
28         Gresik
29         Gresik
30         Gresik
31         Bungah
35        Kebomas
36        Kebomas
37        Kebomas
39         Gresik
40         Gresik
42         Manyar
43        Kebomas
44         Gresik
45        Kebomas
50         Gresik
51        Kebomas
53         Manyar
54         Gresik
55         Gresik
56         Gresik
57        Kebomas
58        Kebomas
59          Cerme
60          Cerme
61          Cerme
63        Kebomas
65         Gresik
67        Kebomas
68         Gresik
69        Kebomas
70         Gresik
Name: Kecamatan, dtype: category
Categories (9, object): ['Benjeng', 'Bungah', 'Cerme', 'Gresik', ..., 'Kedamean', 'Manyar', 'Menganti',
                         'Wringinanom']

In [123]:
try:
    tmp["Rating"] = tmp["Rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
tmp.head()

,Name,Address,Rating,URL,Provinsi,Kota,Kecamatan
0,Makam keluarga H Ilyas Gresik,"XH3C+HCR, Unnamed Road, Area Sawah/Kebun, Bung...",5.0,https://www.google.com/maps/place/Makam+keluar...,Jawa Timur,Gresik,Bungah
2,Pos Hendrosari,"QH3M+G2W, Hendrosalam, Hendrosari, Kec. Mengan...",5.0,https://www.google.com/maps/place/Pos+Hendrosa...,Jawa Timur,Gresik,Menganti
5,Gardoe ANIEM te Grissee,"RMW4+6FW, Jl. Raden Santri, Bedilan, Kebungson...",5.0,https://www.google.com/maps/place/Gardoe+ANIEM...,Jawa Timur,Gresik,Gresik
9,Makam Eyang Kidang Kuning,"VJ34+Q29, Suci, Kec. Manyar, Kabupaten Gresik,...",5.0,https://www.google.com/maps/place/Makam+Eyang+...,Jawa Timur,Gresik,Manyar
11,Gapura KARANG PLOSO,"Dsn karang ploso rt 10, Karangploso, Klampok, ...",4.1,https://www.google.com/maps/place/Gapura+KARAN...,Jawa Timur,Gresik,Benjeng

In [124]:
print(tmp.isnull().sum())
tmp_new = pd.DataFrame()
tmp_new["nama"] = tmp["Name"]
tmp_new["kategori"] = "Taman"
tmp_new["rating"] = tmp["Rating"]
tmp_new["provinsi"] = tmp["Provinsi"]
tmp_new["kota"] = tmp["Kota"]
tmp_new["kecamatan"] = tmp["Kecamatan"]
tmp_new["alamat"] = tmp["Address"]
tmp_new["link"] = tmp["URL"]
tmp_museum = tmp_museum.append(tmp_new, ignore_index=True)

Name         0
Address      0
Rating       0
URL          0
Provinsi     0
Kota         0
Kecamatan    0
dtype: int64

# Taman & Museum Train

In [125]:
print(tmp_taman.shape)
tmp_taman

(829, 8)

,nama,kategori,rating,provinsi,kota,kecamatan,alamat,link
0,Astoria Park,Taman,5.0,Jawa Timur,Surabaya,Mulyorejo,"PQVP+GM4, Jl. Babatan Pantai Bar V, Kalijudan,...",https://www.google.com/maps/place/Astoria+Park...
1,Asia Goldfish Surabaya,Taman,4.7,Jawa Timur,Surabaya,Rungkut,"Jl. Raya Medayu Utara Kav. No. 1 Gerbang biru,...",https://www.google.com/maps/place/Asia+Goldfis...
2,Taman Bermain & Lapangan Futsal,Taman,4.3,Jawa Timur,Surabaya,Benowo,"PJWW+P27, Sememi, Kec. Benowo, Kota SBY, Jawa ...",https://www.google.com/maps/place/Taman+Bermai...
3,Taman Ekspresi Dan Perpustakaan,Taman,4.5,Jawa Timur,Surabaya,Genteng,"Jl. Genteng Kali No.67, Genteng, Kec. Genteng,...",https://www.google.com/maps/place/Taman+Ekspre...
4,Wisata Mangrove Wonorejo Surabaya,Taman,4.5,Jawa Timur,Surabaya,Rungkut,"No., Jl. Wonorejo Timur No.30, Wonorejo, Kec. ...",https://www.google.com/maps/place/Wisata+Mangr...
...,...,...,...,...,...,...,...,...
824,kedanyang park,Taman,4.0,Jawa Timur,Gresik,Kebomas,"RJ88+RR5, Jl. Raya Kedanyang, Sekarkurung, Kec...",https://www.google.com/maps/place/kedanyang+pa...
825,Bukit Awan Water Park Gresik,Taman,3.5,Jawa Timur,Gresik,Kebomas,"Jl. Qomaruddin No.26, Setingi, Randuagung, Kec...",https://www.google.com/maps/place/Bukit+Awan+W...
826,Taman PETROKIMIA PARK,Taman,4.3,Jawa Timur,Gresik,Gresik,"Jl. Cengkeh No.1, Sukodono, Kec. Gresik, Kabup...",https://www.google.com/maps/place/Taman+PETROK...
827,Alun-Alun Gresik,Taman,4.4,Jawa Timur,Gresik,Gresik,"Jl. KH. Wachid Hasyim, Bedilan, Kec. Gresik, K...",https://www.google.com/maps/place/Alun-Alun+Gr...
828,G-Park Gresik,Taman,4.5,Jawa Timur,Gresik,Kebomas,"Jl. Kyai H. Syafiꞌi No.69-70, Dahanrejo, Kec. ...",https://www.google.com/maps/place/G-Park+Gresi...

In [126]:
print(tmp_museum.shape)
tmp_museum

(439, 8)

,nama,kategori,rating,provinsi,kota,kecamatan,alamat,link
0,Monumen Pendidikan,Taman,4.5,Jawa Timur,Surabaya,Wiyung,"MMXF+HM9 Universitas Negeri Surabaya, Lidah We...",https://www.google.com/maps/place/Monumen+Pend...
1,Toko Mainan Micky Mouse Pusat Grosir Surabaya,Taman,5.0,Jawa Timur,Surabaya,Bubutan,"Pusat Grosir Surabaya, Jalan Surabaya Lantai 4...",https://www.google.com/maps/place/Toko+Mainan+...
2,Gedung Parkir Genteng Kali,Taman,4.8,Jawa Timur,Surabaya,Genteng,"PPVV+3FM, Jl. Genteng Kali, RW.11, Genteng, Ke...",https://www.google.com/maps/place/Gedung+Parki...
3,Universitas Dinamika (STIKOM Surabaya),Taman,4.8,Jawa Timur,Surabaya,Rungkut,"Jl. Raya Kedung Baruk No.98, Kedung Baruk, Kec...",https://www.google.com/maps/place/Universitas+...
4,Balai Pemuda Surabaya,Taman,4.7,Jawa Timur,Surabaya,Genteng,"Jl. Gubernur Suryo No.15, Embong Kaliasin, Kec...",https://www.google.com/maps/place/Balai+Pemuda...
...,...,...,...,...,...,...,...,...
434,Kampoeng Pentol,Taman,5.0,Jawa Timur,Gresik,Gresik,"RJPR+MR5, Jl. DR. Sutomo Gg. XIV, Trate, Kec. ...",https://www.google.com/maps/place/Kampoeng+Pen...
435,Tugu SGF,Taman,4.4,Jawa Timur,Gresik,Kebomas,"RJFW+78H, Perdin SG blok G, Jl. Awikoen, Kb. D...",https://www.google.com/maps/place/Tugu+SGF/@-7...
436,Sunan MMI Gresik,Taman,4.0,Jawa Timur,Gresik,Gresik,"RMQ3+WJW, Tlogobendung, Bedilan, Kec. Gresik, ...",https://www.google.com/maps/place/Sunan+MMI+Gr...
437,"Museum Daerah Kabupaten Gresik ""Sunan Giri""",Taman,5.0,Jawa Timur,Gresik,Kebomas,"Jl. Sunan Giri, Pedukuhan, Kebomas, Kec. Kebom...",https://www.google.com/maps/place/Museum+Daera...
438,Museum Sunan Giri,Taman,4.3,Jawa Timur,Gresik,Gresik,"No, Jl. Pahlawan No.24, Tlogobendung, Bedilan,...",https://www.google.com/maps/place/Museum+Sunan...

# Taman NTT

In [127]:
taman_ntt = pd.read_csv("/content/drive/MyDrive/Healing.ai/taman_ntt.csv")
taman_ntt.dropna(subset = ["nama", "rating"], inplace=True)
try:
    taman_ntt["rating"] = taman_ntt["rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
taman_ntt["rating"].dtypes

dtype('float64')

In [128]:
print(taman_ntt["kategori"].value_counts())
print(taman_ntt["provinsi"].value_counts())
print(taman_ntt["kota"].value_counts())
print(taman_ntt["kecamatan"].value_counts())

Taman    19
Name: kategori, dtype: int64
NTT    19
Name: provinsi, dtype: int64
Kupang                  13
Ende                     2
Manggarai Barat          1
Ngada                    1
Sikka                    1
Timur Tengah Selatan     1
Name: kota, dtype: int64
Kelapa  Lima     3
Kota Raja        3
Oebobo           2
Kota Lama        1
Komodo           1
Kupang Tengah    1
Maulafa          1
Kupang Barat     1
Fatuleu          1
Detusoko         1
Kupang Timur     1
Riung            1
Nelle            1
Mollo Utara      1
Name: kecamatan, dtype: int64

# Museum NTT

In [129]:
museum_ntt = pd.read_csv("/content/drive/MyDrive/Healing.ai/museum_ntt.csv")
museum_ntt.dropna(subset = ["nama", "rating"], inplace=True)
try:
    taman_ntt["rating"] = taman_ntt["rating"].str.replace(",", ".").astype(float)
except:
    print("Udah Benar")
museum_ntt["rating"].dtypes

Udah Benar

dtype('float64')

In [130]:
museum_ntt["kota"].replace("Sumba Barat daya", "Sumba Barat Daya", inplace=True)

In [131]:
print(museum_ntt["kategori"].value_counts())
print(museum_ntt["provinsi"].value_counts())
print(museum_ntt["kota"].value_counts())
print(museum_ntt["kecamatan"].value_counts())

Museum    10
Name: kategori, dtype: int64
NTT    10
Name: provinsi, dtype: int64
Kota Kupang         3
Sumba Barat Daya    2
Ende                2
Alor                2
Sikka               1
Name: kota, dtype: int64
Kota Raja                      2
Kodi Utara                     1
Nita                           1
Kelapa Lima                    1
Oebobo                         1
Potulando                      1
Teluk Mutiara                  1
Kalembu Nga'banga Waitabula    1
Alor Barat Laut                1
Name: kecamatan, dtype: int64

# Taman & Museum Test

In [132]:
print(taman_ntt.shape)
taman_ntt

(19, 8)

,nama,kategori,rating,provinsi,kota,kecamatan,alamat,link
0,Taman Ina Bo'i,Taman,4.6,NTT,Kupang,Kelapa Lima,Jl. RA Kartini,https://www.google.com/maps/place/Taman+Ina+Bo...
1,Taman Palapa,Taman,5.0,NTT,Kupang,Oebobo,Jl. Palapa dekat Jl. Cak Doko,https://www.google.com/maps/place/Taman+Palapa...
2,Taman Kota Fontein,Taman,4.1,NTT,Kupang,Kota Raja,Fontein,https://www.google.com/maps/place/Taman+Kota+F...
4,Taman Sonbai,Taman,5.0,NTT,Kupang,Kota Lama,"Jl. Moch Hatta, Merdeka",https://www.google.com/maps/place/Taman+Sonbai...
5,Taman Nostalgia,Taman,4.3,NTT,Kupang,Oebobo,"Jl.Frans Seda, Oebufu",https://www.google.com/maps/place/Nostalgia+Pa...
6,Taman Nasional Komodo,Taman,4.7,NTT,Manggarai Barat,Komodo,Labuan Bajo,https://www.google.com/maps/place/Komodo+Natio...
7,Taman Renungan Bung Karno,Taman,4.4,NTT,Ende,Kota Raja,Jln.Perwira,https://www.google.com/maps/place/Bung+Karno+C...
8,Taman Bunga & Kincir Angin Oebelo Indah,Taman,4.4,NTT,Kupang,Kupang Tengah,"Diantara Pos Polisi, dan Gereja Kalvari Oebelo...",https://www.google.com/maps/place/Taman+Bunga+...
9,DMCC Garden,Taman,5.0,NTT,Kupang,Maulafa,Fatukoa,https://www.google.com/maps/place/DMCC+Garden/...
10,Gong Perdamaian,Taman,4.4,NTT,Kupang,Kelapa Lima,"Jl. koperasi, Liliba",https://www.google.com/maps/place/Gong+Perdama...
11,Alun-Alun Kota Kupang,Taman,4.5,NTT,Kupang,Kelapa Lima,Jl.Timor Raya,https://www.google.com/maps/place/Alun-Alun+Ko...
12,Taman Wisata Boneana,Taman,4.4,NTT,Kupang,Kupang Barat,"Dusun Boneana, Oemat Nunu",https://www.google.com/maps/place/Taman+Wisata...
13,Nature Camplong,Taman,4.0,NTT,Kupang,Fatuleu,"Jl. Oesao - Bokong, Camplong I",https://www.google.com/maps/place/Nature+Campl...
14,Kelimutu National Park,Taman,4.7,NTT,Ende,Detusoko,Danau Kelimutu,https://www.google.com/maps/place/Kelimutu+Nat...
15,Jiwan's Garden,Taman,4.3,NTT,Kupang,Kupang Timur,Oesao II,https://www.google.com/maps/place/Jiwan's+Gard...
16,Taman Wisata Arjuna,Taman,4.2,NTT,Kupang,Kota Raja,Bakunase II,https://www.google.com/maps/place/Taman+Wisata...
17,Taman Wisata Alam Laut 17 Pulau Riung,Taman,4.5,NTT,Ngada,Riung,Pulau Ontoloe,https://www.google.com/maps/place/17+Islands+N...
18,Taman Replica Betlehem,Taman,4.5,NTT,Sikka,Nelle,"Kampung Kloang Bola, Desa Nelle Wutung",https://www.google.com/maps/place/Taman+Replic...
19,Taman Wisata Bukit bakium gunung mutis\r\n,Taman,4.1,NTT,Timur Tengah Selatan,Mollo Utara,Tunua,https://www.google.com/maps/place/Bukit+bakium...

In [133]:
print(museum_ntt.shape)
museum_ntt

(10, 8)

,nama,kategori,rating,provinsi,kota,kecamatan,alamat,link
0,Kalimbatu Monggo,Museum,3.3,NTT,Sumba Barat Daya,Kodi Utara,"Monggo, Desa Waiha, Bakaghar, Barat Daya, Kale...",https://wwI2:P4place/Kalimbatu+Monggo/@-9.6365...
1,Museum Bikon Blewut,Museum,4.1,NTT,Sikka,Nita,"Jln raya maumere - ende, STFK Ledalero, Desa T...",https://www.google.com/maps/place/Museum+Bikon...
2,Museum El Tari,Museum,3.9,NTT,Kota Kupang,Kota Raja,Fontein,https://www.google.com/maps/place/Museum+El+Ta...
3,Museum Negeri Kupang,Museum,4.0,NTT,Kota Kupang,Kelapa Lima,"Jl. Eltari 2, Oesapa Selatan",https://www.google.com/maps/place/Museum+Neger...
4,NTT Regional Museum,Museum,4.4,NTT,Kota Kupang,Oebobo,"Kayu Putih, Oebobo",https://www.google.com/maps/place/NTT+Regional...
5,Museum Tenun Ikat,Museum,3.7,NTT,Ende,Kota Raja,"Kel. Kotaraja, Ende Utara",https://www.google.com/maps/place/Museum+Tenun...
6,Serambi Soekarno,Museum,4.8,NTT,Ende,Potulando,"Kel. Potulando, Ende Tengah",https://www.google.com/maps/place/Serambi+Soek...
7,Museum Kalabahi,Museum,4.3,NTT,Alor,Teluk Mutiara,Nusa Kenari,https://www.google.com/maps/place/Museum+Kalab...
8,Rumah Budaya Sumba,Museum,4.5,NTT,Sumba Barat Daya,Kalembu Nga'banga Waitabula,Jl. Rumah Budaya No.212,https://www.google.com/maps/place/Rumah+Budaya...
9,Rumah Al-qur'an Tua ( Kulit Kayu ),Museum,4.3,NTT,Alor,Alor Barat Laut,Alor Besar,https://www.google.com/maps/place/Rumah+Al-qur...

In [134]:
taman = pd.concat([tmp_taman, taman_ntt])
taman.to_csv("taman.csv", index=False)
museum = pd.concat([tmp_museum, museum_ntt])
museum.to_csv("museum.csv", index=False)
print(taman.shape)
print(museum.shape)

(848, 8)
(449, 8)

# Modelling berbasis Content-Based Filtering

## Modelling dataset Taman

In [135]:
# Mengimpor library TfidfVectorizer untuk pemodelan Content-Based Filtering
from sklearn.feature_extraction.text import TfidfVectorizer
 
# Inisialisasi TfidfVectorizer
tf = TfidfVectorizer()
 
# Melakukan perhitungan idf pada kolom kecamatan
tf.fit(taman_cbf['kecamatan'])
 
# Mendata penerbit buku pada data taman_cbf
tf.get_feature_names()

# Melakukan fit lalu ditransformasikan ke bentuk dataframe
tfidf_matrix = tf.fit_transform(taman_cbf['kecamatan'])
 
# Melihat ukuran dataframe tfidf
tfidf_matrix.shape

# Mengubah vektor tf-idf dalam bentuk matriks dengan fungsi todense()
tfidf_matrix.todense()

# Membuat dataframe untuk melihat tf-idf matrix
# Baris diisi dengan judul buku
# Kolom diisi dengan penerbit buku

pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tf.get_feature_names(),
    index=taman_cbf['nama']
).sample(5, axis=0).sample(5, axis=1)

NameError: ignored

In [ ]:
# Mengimpor library cosine_similarity untuk pemodelan Content-Based Filtering
from sklearn.metrics.pairwise import cosine_similarity
 
# Menghitung cosine similarity pada matrix tf-idf
cosine_sim = cosine_similarity(tfidf_matrix)

# Menampilkan array hasil komputasi fungsi cosine_similarity
cosine_sim

In [ ]:
# Membuat dataframe dari variabel cosine_sim dengan baris dan kolom berupa nama
cosine_sim_df = pd.DataFrame(cosine_sim, index=taman_cbf['nama'], columns=taman_cbf['nama'])

# Menampilkan bentuk data cosine_sim_df
print('Bentuk :', cosine_sim_df.shape)
 
# Melihat similarity matrix pada setiap buku
cosine_sim_df.sample(5, axis=0).sample(5, axis=1)

In [ ]:
# Membuat fungsi rekomendasi data untuk Content-Based Filtering
def rekomendasi_taman_cbf(nama, similarity_data=cosine_sim_df, items=taman_cbf[['nama', 'kategori', 'rating', 'kecamatan', 'kota', 'provinsi', 'alamat', 'link']], k=20):
    """
    Rekomendasi data berdasarkan kemiripan dataframe
 
    Parameter:
    ---
    nama : tipe data string (str)
                Nama data (index kemiripan dataframe)
    similarity_data : tipe data pd.DataFrame (object)
                      Kesamaan dataframe, simetrik, dengan nama data sebagai 
                      indeks dan kolom
    items : tipe data pd.DataFrame (object)
            Mengandung kedua nama dan fitur lainnya yang digunakan untuk mendefinisikan kemiripan
    k : tipe data integer (int)
        Banyaknya jumlah rekomendasi yang diberikan
    ---
 
 
    Pada index ini, kita mengambil k dengan nilai similarity terbesar 
    pada index matrix yang diberikan (i).
    """

    # Mengambil data dengan menggunakan argpartition untuk melakukan partisi secara tidak langsung sepanjang sumbu yang diberikan    
    # Dataframe diubah menjadi numpy
    # Range(start, stop, step)
    index = similarity_data.loc[:,nama].to_numpy().argpartition(range(-1, -k, -1))
    
    # Mengambil data dengan similarity terbesar dari index yang ada
    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    
    # Drop nama agar nama data yang dicari tidak muncul dalam daftar rekomendasi
    closest = closest.drop(nama, errors='ignore')
 
    return pd.DataFrame(closest).merge(items).head(k)

In [ ]:
# Menampilkan data terkait buku yang berjudul 'Taman Ekspresi Dan Perpustakaan' pada data taman_cbf
taman_cbf[taman_cbf['nama'].eq('Taman Ekspresi Dan Perpustakaan')]

In [ ]:
# Menampilkan rekomendasi taman yang mirip dengan taman bernama 'Taman Ekspresi Dan Perpustakaan'
hasil_rekomendasi_taman_cbf = rekomendasi_taman_cbf('Taman Ekspresi Dan Perpustakaan')
hasil_rekomendasi_taman_cbf

## Modelling dataset Museum

# Modelling berbasis Collaborative Filtering

## Modelling dataset Taman

In [ ]:
# Mengimpor modul train_test_split dari library sklearn untuk pendukung pembagian data
from sklearn.model_selection import train_test_split

# Mengacak data untuk Collaborative Filtering dari data asli
df_cf = df.sample(frac=1, random_state=123)

# Menggunakan seperseratus data asli untuk Collaborative Filtering
# Menampung pada variabel df_cf
df_cf = df_cf[:len(df)//10]

# Menampilkan jumlah data untuk pemodelan berbasis Collaborative Filtering
print(len(df_cf))

# Mendata nilai fitur id_pengguna yang unik
id_pengguna = df_cf['id_pengguna'].unique().tolist()

# Mendata nilai fitur id_buku yang unik
id_buku = df_cf['id_buku'].unique().tolist()

# Memetakan id_pengguna dan indeks mulai 0 hingga jumlah total data id_pengguna
id_pengguna_dan_indeks = {id_pengguna: indeks for indeks, id_pengguna in enumerate(id_pengguna)}

# Memetakan id_buku dan indeks mulai 0 hingga jumlah total data id_buku
id_buku_dan_indeks = {id_buku: indeks for indeks, id_buku in enumerate(id_buku)}

# Memetakan indeks mulai 0 hingga jumlah total data id_pengguna dan id_pengguna
indeks_dan_id_pengguna = {indeks: id_pengguna for indeks, id_pengguna in enumerate(id_pengguna)}

# Memetakan indeks mulai 0 hingga jumlah total data id_buku dan id_buku
indeks_dan_id_buku = {indeks: id_buku for indeks, id_buku in enumerate(id_buku)}

# Menambahkan fitur indeks_id_pengguna yang merupakan hasil pemetaan id_pengguna menjadi indeks yang unik
df_cf['indeks_id_pengguna'] = df_cf['id_pengguna'].map(id_pengguna_dan_indeks)

# Menambahkan fitur indeks_id_buku yang merupakan hasil pemetaan id_buku menjadi indeks yang unik
df_cf['indeks_id_buku'] = df_cf['id_buku'].map(id_buku_dan_indeks)

# Menampung jumlah id_pengguna unik
jumlah_pengguna = len(id_pengguna_dan_indeks)

# Menampilkan jumlah pengguna
print(jumlah_pengguna)

# Menampung jumlah id_buku unik
jumlah_buku = len(id_buku_dan_indeks)

# Menampilkan jumlah buku
print(jumlah_buku)

# Menampung nilai minimal dari rating_buku pada data df_cf
min_rating = min(df_cf['rating_buku'])

# Menampung nilai maksimal dari rating_buku pada data df_cf
max_rating = max(df_cf['rating_buku'])

# Membuat variabel x untuk mencocokkan data pengguna dan buku menjadi satu value
X = df_cf[['indeks_id_pengguna', 'indeks_id_buku']].values
 
# Membuat variabel y untuk membuat kemiripan rating pada rentang 0-1
y = df_cf['rating_buku'].apply(lambda x: (x - min_rating) / (max_rating - min_rating)).values
 
# Membagi masukan (X) dan hasil masukan (y) dengan persentase data validasi 20%
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

# Menampilkan bentuk fitur masukan pada data latih Collaborative Filtering
print(X_train.shape)

# Menampilkan bentuk fitur target pada data latih Collaborative Filtering
print(y_train.shape)

In [ ]:
# Import library tensorflow untuk pengembangan Deep Learning
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Membuat kelas RecommenderNet untuk pemodelan terkait sistem rekomendasi
class RecommenderNet(tf.keras.Model):
 
  # Inisialisasi parameter kelas
  def __init__(self, jumlah_pengguna, jumlah_buku, ukuran_embedding, **kwargs):

    # Pewarisan parameter - paramter pada kelas
    super(RecommenderNet, self).__init__(**kwargs)

    # Inisialisasi variabel kelas
    self.jumlah_pengguna = jumlah_pengguna
    self.jumlah_buku = jumlah_buku
    self.ukuran_embedding = ukuran_embedding

    # Inisialisasi layer embedding terhadap data pengguna
    self.embedding_pengguna = layers.Embedding(
        jumlah_pengguna,
        ukuran_embedding,
        embeddings_initializer='he_normal',
        embeddings_regularizer=keras.regularizers.l2(1e-6)
    )

    # Inisialisasi layer embedding terhadap bias pada data pengguna
    self.bias_pengguna = layers.Embedding(jumlah_pengguna, 1)

    # Inisialisasi layer embedding terhadap data buku
    self.embedding_buku = layers.Embedding(
        jumlah_buku,
        ukuran_embedding,
        embeddings_initializer='he_normal',
        embeddings_regularizer=keras.regularizers.l2(1e-6)
    )

    # Inisialisasi layer embedding terhadap bias pada data buku
    self.bias_buku = layers.Embedding(jumlah_buku, 1)
 
  # Inisialisasi fungsi pemanggilan input bagi model Deep Learning
  def call(self, inputs):

    # Inisialisasi layer embedding untuk vektor pengguna
    vektor_pengguna = self.embedding_pengguna(inputs[:,0])

    # Inisialisasi layer embedding untuk bias_pengguna
    bias_pengguna = self.bias_pengguna(inputs[:,0])

    # Inisialisasi layer embedding untuk vektor_buku
    vektor_buku = self.embedding_buku(inputs[:,1])

    # Inisialisasi layer embedding untuk bias_buku
    bias_buku = self.bias_buku(inputs[:,1])

    # Menghitung perkalian matriks vektor_pengguna dan vektor_buku pada axes 2
    titik_pengguna_dan_buku = tf.tensordot(vektor_pengguna, vektor_buku, 2) 

    # Menjumlahkan hasil perkalian matriks dengan bias_pengguna dan bias_buku pada variabel x
    x = titik_pengguna_dan_buku + bias_pengguna + bias_buku
    
    # Melakukan aktivasi dengan fungsi sigmoid pada variabel x
    return tf.nn.sigmoid(x)

In [ ]:


# Membuat model berbasis RecommenderNet dengan parameter yang telah dibuat
model = RecommenderNet(jumlah_pengguna, jumlah_buku, 50)
 
# Mengompile model dengan optimizer, loss, dan metrik yang relevan
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

In [ ]:
# Melatih model dengan epoch 10 dan batch_size 8 dan data latih serta data validasi
history = model.fit(
    x=X_train,
    y=y_train,
    batch_size=8,
    epochs=10,
    validation_data=(X_val,y_val)
)

In [ ]:
# Mengambil data pengguna secara acak dari data df_cf
id_pengguna_prediksi = df_cf['id_pengguna'].sample(1).iloc[0]

# Menampung data buku yang disukai oleh pengguna
buku_disukai_pengguna = df_cf[df_cf['id_pengguna']==id_pengguna_prediksi]

# Menampung data buku yang belum diketahui oleh pengguna untuk ditentukan mana saja buku
# yang dapat direkomendasikan kepada pengguna tersebut
buku_tak_diketahui_pengguna = df_cf[~df_cf['id_buku'].isin(buku_disukai_pengguna['id_buku'].values)]['id_buku']
buku_tak_diketahui_pengguna = list(set(buku_tak_diketahui_pengguna).intersection(set(id_buku_dan_indeks.keys())))
buku_tak_diketahui_pengguna = [[id_buku_dan_indeks.get(x)] for x in buku_tak_diketahui_pengguna]

# Menampung indeks unik dari id_pengguna
indeks_id_pengguna = id_pengguna_dan_indeks.get(id_pengguna_prediksi)

# Mengimpor library numpy untuk mendukung pengolahan array
import numpy as np

# Menampung gabungan data indeks unik dari id_pengguna dan indeks unik dari buku yang belum diketahui oleh pengguna
# untuk menjadi data masukan guna prediksi rekomendasi buku
array_pengguna_dan_buku = np.hstack(([[indeks_id_pengguna]] * len(buku_tak_diketahui_pengguna), buku_tak_diketahui_pengguna))

# Menampilkan data masukan guna prediksi rekomendasi buku
array_pengguna_dan_buku

In [ ]:
# Menampilkan antarmuka yang friendly untuk rekomendasi buku bagi pengguna
print('Rekomendasi Buku Untuk Pengguna {}'.format(id_pengguna_prediksi))
print('====' * 10)
print('Buku Favorit Pengguna')
print('----' * 10)

# Menampung data buku yang disukai oleh pengguna dengan diurutkan berdasarkan rating tertinggi
buku_favorit_pengguna = buku_disukai_pengguna.sort_values(by='rating_buku', ascending=False)[:10]

# Menampilkan data buku yang disukai oleh pegguna
for index, row in buku_favorit_pengguna.iterrows():
    print(row['judul_buku'], '-', row['penerbit_buku'])

# Menampilkan antarmuka yang friendly untuk rekomendasi buku bagi pengguna
print('----' * 10)
print('10 Besar Rekomendasi Buku')
print('----' * 10)

# Melakukan prediksi rekomendasi buku berdasarkan data masukan yang telah dibuat
hasil_prediksi = model.predict(array_pengguna_dan_buku).flatten()

# Mengurutkan hasil prediksi berdasarkan tingkat akurasi tertinggi
sepuluh_besar_hasil_prediksi = hasil_prediksi.argsort()

# Menampung data rekomendasi buku dari hasil prediksi
rekomendasi_buku_cf = [indeks_dan_id_buku.get(buku_tak_diketahui_pengguna[x][0]) for x in sepuluh_besar_hasil_prediksi]
rekomendasi_buku_cf = df_cf[df_cf['id_buku'].isin(rekomendasi_buku_cf)]

# Mengambil data rekomendasi buku yang disesuaikan dengan preferensi buku yang disukai oleh pengguna
rekomendasi_buku_cf = rekomendasi_buku_cf[rekomendasi_buku_cf['penerbit_buku'].isin(buku_favorit_pengguna['penerbit_buku'].values)]

# Menghapus data duplikat pada data rekomendasi buku
rekomendasi_buku_cf.drop_duplicates('judul_buku', inplace=True)

# Menampilkan 10 besar data rekomendasi buku bagi pengguna
for index, row in rekomendasi_buku_cf[:10].iterrows():
    print(row['judul_buku'], '-', row['penerbit_buku'])